### PR TITLE
chore(launcher): improve launcher logging & fix some error handling. Fixes #5882

### LINKED ISSUE #5882: [launcher] make debugging launcher easier
KFP v2 compatible launcher doesn't log anything unless an error occurs, therefore when there's an launcher logic error. It's very hard to debug what actually happened.

Propose inventing some mechanism to support this use-case.

## Option 1 - add basic logging which is turned on by default

Pros:
* we can always find some information in logs

Cons:
* confusing to users, because launcher log is now mixing with user component logs

## Option 2 - add a config that can turn on verbose launcher logging

Pros: minimal confusion usually
Cons: the complexity to design the config switch & efforts to turn it on & rerun a pipeline is huge

What do you think? Are there better options?

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Fixes #5882 

Changes:
* make launcher log more things by default, and one flag can be used to easily enable info logging
* fix some error handling
* add stricter validation for artifact `metadataPath`

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: v2/cmd/launch/main.go [hunk 1]
```diff
@@ -55,3 +56,11 @@ func main() {
 		glog.Exitf("Failed to execute component: %v", err)
 	}
 }
+
+func init() {
+	// Change default logging level to facilitate debugging
+	flag.Set("logtostderr", "true")
+	flag.Set("stderrthreshold", "WARNING")
+	// Uncomment the following to enable INFO level logging.
+	// flag.Set("stderrthreshold", "INFO")
```
Comment (neuromage) [inline v2/cmd/launch/main.go:65]: Instead of this line, consider adding a comment above to instruct user to change "WARNING" to "INFO"

File: v2/component/launcher.go [hunk 2]
```diff
@@ -389,16 +390,18 @@ func (l *Launcher) RunComponent(ctx context.Context, cmdArgs []string) error {
...
-				return fmt.Errorf("failed to upload output artifact %q to remote storage URI %q: %w", name, outputArtifact.Uri, err)
+		} else {
+			blobKey, err := l.bucketConfig.keyFromURI(outputArtifact.Uri)
+			if err != nil {
+				return fmt.Errorf("failed to upload output artifact %q: %w", name, err)
+			}
+			if err := uploadBlob(ctx, bucket, localDir, blobKey); err != nil {
+				//  We allow components to not produce output files
+				if errors.Is(err, os.ErrNotExist) {
+					glog.Warningf("local filepath %q does not exist", localDir)
```
Comment (neuromage) [inline v2/component/launcher.go:401]: nit: Capitalize first word of log messages.

File: v2/component/runtime_info.go [hunk 3]
```diff
@@ -322,6 +323,9 @@ func (r *runtimeInfo) generateExecutorInput(genOutputURI generateOutputURI, outp
 		if len(ia.MetadataPath) == 0 {
 			return nil, fmt.Errorf("missing input artifact metadata file for input %q", name)
 		}
+		if !filepath.IsAbs(ia.MetadataPath) {
+			return nil, fmt.Errorf("unexpected input artifact metadata file %q for input %q", ia.MetadataPath, name)
```
Comment (neuromage) [inline v2/component/runtime_info.go:327]: add message it must be absolute path?

File: v2/component/launcher.go [hunk 4]
```diff
@@ -427,6 +430,9 @@ func (l *Launcher) RunComponent(ctx context.Context, cmdArgs []string) error {
 		})
 
 		rtoa, ok := l.runtimeInfo.OutputArtifacts[name]
+		if !filepath.IsAbs(rtoa.MetadataPath) {
+			return metadataErr(fmt.Errorf("unexpected output artifact metadata file %q: must be absolute local path", rtoa.MetadataPath))
```
Comment (neuromage) [inline v2/component/launcher.go:434]: When does this happen btw?

**Review by neuromage — COMMENTED** [review]
/lgtm

File: v2/component/launcher.go (hunk 4 above)
Comment (Bobgy) [reply v2/component/launcher.go:434]: I reproduced this problem when running https://github.com/amygdala/code-snippets/blob/master/ml/vertex_pipelines/pytorch/cifar/pytorch_cifar10_vertex_pipelines.ipynb in v2 compatible mode. I don't understand why that happened. (There are more details in chat group)

**Comment by Bobgy** [comment]
Welcome follow up feedback as I merge the PR.
