### PR TITLE
fix(backend): fixes useless error message when visualization-server is not accessible. Fixes #4157

### LINKED ISSUE #4157: No information in error message when visualization server is not accessible
https://github.com/kubeflow/pipelines/blob/bd0f4d23b9e73082a3924d9f3869bbe537639557/backend/src/apiserver/server/visualization_server.go#L82

When visualization server is not responding, error message in api server is not helpful at all. It should show upstream error message to help troubleshooting.

### PR DESCRIPTION
**Pull request by PatrickXYS**
**Description of your changes:**
Fixes #4157 

### What we have before:

When visualization server is not accessible, the error message only mentions: `Service not available`, this doesn't provide enough context and information for users/developers to debug.

### What we have now:
When visualization server is not accessible, the error message is: `visualization server is not responsible`, which provides more information and context. 

### Test we made every time before pushing:
`bazel test //backend/src/apiserver/server:go_default_test --test_filter=TestListRuns_Pagination --test_output=all`

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

   PR titles examples:
    * `fix(frontend): fixes empty page. Fixes #1234`
       Use `fix` to indicate that this PR fixes a bug.
    * `feat(backend): configurable service account. Fixes #1234, fixes #1235`
       Use `feat` to indicate that this PR adds a new feature. 
    * `chore: set up changelog generation tools`
       Use `chore` to indicate that this PR makes some changes that users don't need to know.
    * `test: fix CI failure. Part of #1234`
        Use `part of` to indicate that a PR is working on an issue, but shouldn't close the issue when merged.

- [ ] Do you want this pull request (PR) cherry-picked into the current release branch?
    
    If yes, use one of the following options:
  
    * **(Recommended.)** Ask the PR approver to add the `cherrypick-approved` label to this PR. The release manager adds this PR to the release branch in a batch update.
    *  After this PR is merged, create a cherry-pick PR to add these changes to the release branch. (For more information about creating a cherry-pick PR, see the [Kubeflow Pipelines release guide](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#option--git-cherry-pick).)

### CODE REVIEW

**Comment by PatrickXYS** [comment]
/assign @Bobgy 

Hi @Bobgy , I'm not sure if the error message that I change is good enough (I guess not), would you mind sharing more insights about what exact error message you want if you think this is not enough?

File: backend/src/apiserver/server/visualization_server.go [hunk 1]
```diff
@@ -80,8 +80,8 @@ func (s *VisualizationServer) generateVisualizationFromRequest(request *go_clien
 	serviceURL := s.getVisualizationServiceURL(request)
 	if !isVisualizationServiceAlive(serviceURL) {
 		return nil, util.NewInternalServerError(
-			fmt.Errorf("service not available"),
-			"Service not available",
+			fmt.Errorf("visualization server is not responsible"),
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:83]: Thanks! This is better than before.

One more info I wanted is that, when calling `isVisualizationServiceAlive`, it just returns whether alive or not. However, the root cause might come from many different reasons. For example, misconfigured istio setting preventing visualization service being reached.

Therefore, I think it's better refactoring `isVisualizationServiceAlive` to return an error instead. Then, the error we return here can be a wrapper on that error like usage in https://github.com/kubeflow/pipelines/blob/b1c1431eb8d6b7cc63c55f5e828faf9859a50e55/backend/src/apiserver/server/experiment_server.go#L28

If we change it like this, each time when `isVisualizationServiceAlive` fails, we can easily debug what went wrong from the browser instead of looking into logs from different servers.

Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go]: Thanks for explanation!

So apart from using `util.Wrap()`, I tried to use `errors.New()` to bring up sufficient error message in `isVisualizationServiceAlive `.

File: backend/src/apiserver/server/visualization_server.go [hunk 2]
```diff
@@ -115,13 +112,12 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
 	return s.serviceURL
 }
 
-func isVisualizationServiceAlive(serviceURL string) bool {
-	resp, err := http.Get(serviceURL)
-	if err != nil {
-		glog.Error("Unable to verify visualization service is alive!", err)
-		return false
+func isVisualizationServiceAlive(serviceURL string) (bool, error) {
+	resp, _ := http.Get(serviceURL)
```
Comment (PatrickXYS) [inline backend/src/apiserver/server/visualization_server.go:116]: So I did some investigation and what happened here in `TestGenerateVisualization_ServiceNotAvailableError`:
```
resp, err := http.Get(serviceURL) # resp.StatusCode != http.StatusOK and err == nil
```
So I don't think we can simply use:

```
return false, util.Wrap(err, "ERROR MESSAGE HERE") 
```

Because `util.Wrap(err, "ERROR MESSAGE HERE") ` will be `nil` if `err == nil`

Comment (Bobgy) [reply backend/src/apiserver/server/visualization_server.go:116]: Good point! I didn't know this.

Based on this new information, then error can come from:
* `http.Get`'s err -> network errors etc (you can read http.Get documentation for when error shows up), detailed root cause can be found at `err`
* request succeeded but resp.statusCode is not ok -> resp.status and resp.body might contain information about why it failed

So I think it'll be better if we can propagate error for both cases:
* when there is an error, we can use `util.Wrap(err, '....')`
* when statuscode not OK, we can return `resp.status` inside the error because resp.status should be short
  and log `resp.body` using `glog.Error`, because it can be long.

The benefit will be when there's an error, we can get all the failure information without adding rebuilding api server and adding logging there.

Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:116]: Thanks for providing more insights! I made more investigations and some changes to address your comments.



The lifecycle of `TestGenerateVisualization_ServiceNotAvailableError` unit test:

1. Create necessary resources including `server `and `request`.
2. Then make a call `generateVisualizationFromRequest`: when we reach out to `resp, err := http.Get(serviceURL)`, in our case, it will return non-nil `resp` and `err == nil` when get a `non-2xx response (It's 500 in test)`
3. So the `resp.Status` will always be `500 Internal Server Error `.



Thus, users will be able to see similar logs as below when vis-server is not accessible:

```
Unable to verify visualization service is alive by sending request to http://127.0.0.1:53545 and get 500 Internal Server Error !
```

Comment (Bobgy) [reply backend/src/apiserver/server/visualization_server.go:116]: Thanks, the case coverred in unit test is good now.

Would you mind adding handling for
> http.Get's err -> network errors etc (you can read http.Get documentation for when error shows up), detailed root cause can be found at err

?

I think you can reproduce this case by connecting to a non existant host in unit test.

Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:116]: I'm not sure if I understand correctly, from my understanding, what you want:

In unit test, we create `server` with non-existing host, and then `http.Get()` will return `err != nil`. Can you correct me if I'm wrong?

But I'm not sure if this is the expected behavior for `TestGenerateVisualization_ServiceNotAvailableError ` test, or you're talking about adding another unit test to handle the behavior you mentioned:

> http.Get's err -> network errors etc (you can read http.Get documentation for when error shows up), detailed root cause can be found at err

Comment (Bobgy) [reply backend/src/apiserver/server/visualization_server.go:116]: > In unit test, we create server with non-existing host, and then http.Get() will return err != nil

Correct!

> or you're talking about adding another unit test to handle the behavior you mentioned

Exactly, this should be a new unit test.

Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go]: Thanks for explanations! I added another unit test to handle `ServerHostNotExistError`.

File: backend/src/apiserver/server/visualization_server.go [hunk 3]
```diff
@@ -115,13 +112,14 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
...
-func isVisualizationServiceAlive(serviceURL string) bool {
+func isVisualizationServiceAlive(serviceURL string) (bool, error) {
 	resp, err := http.Get(serviceURL)
-	if err != nil {
-		glog.Error("Unable to verify visualization service is alive!", err)
-		return false
+	if resp != nil && resp.StatusCode != http.StatusOK {
+		return false, errors.New(fmt.Sprintf("Unable to verify visualization service is alive by sending request to %s and get %s !", serviceURL, resp.Status))
+	} else if resp == nil && err != nil {
+		return false, util.Wrap(err, "The visualization server host not exist!")
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:120]: nit: when there's an error here, it doesn't always mean visualization server host doesn't exist.
`util.Wrap` keeps internal err's message, so in this layer, we just need to tell "what we are trying to do, and it failed"

Therefore, I'd suggest
```
return false, util.Wrap(err, fmt.Sprintf("Unable to verify visualization service is alive by sending request to %s", serviceURL))
```

File: backend/src/apiserver/server/visualization_server_test.go [hunk 4]
```diff
@@ -155,7 +155,29 @@ func TestGenerateVisualization_ServiceNotAvailableError(t *testing.T) {
...
+		Type:      go_client.Visualization_ROC_CURVE,
+		Source:    "gs://ml-pipeline/roc/data.csv",
+		Arguments: "{}",
+	}
+	request := &go_client.CreateVisualizationRequest{
+		Visualization: visualization,
+	}
+	body, err := server.generateVisualizationFromRequest(request)
+	assert.Nil(t, body)
+	assert.Contains(t, err.Error(), "The visualization server host not exist")
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server_test.go:180]: Can we assert on the internal err's message? so that we can be sure internal error message is properly wrapped and exposed to the user.

File: backend/src/apiserver/server/visualization_server.go [hunk 5]
```diff
@@ -115,13 +112,14 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
 	return s.serviceURL
 }
 
-func isVisualizationServiceAlive(serviceURL string) bool {
+func isVisualizationServiceAlive(serviceURL string) (bool, error) {
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:115]: nit: returning the bool is now kind of redundant. We can just return the error. If error is not nil, it failed.

File: backend/src/apiserver/server/visualization_server.go [hunk 6]
```diff
@@ -115,13 +112,14 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
...
 	resp, err := http.Get(serviceURL)
-	if err != nil {
-		glog.Error("Unable to verify visualization service is alive!", err)
-		return false
+	if resp != nil && resp.StatusCode != http.StatusOK {
+		return false, errors.New(fmt.Sprintf("Unable to verify visualization service is alive by sending request to %s and get %s !", serviceURL, resp.Status))
+	} else if resp == nil && err != nil {
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:119]: nit: `resp` is not necessarily nil when there is an `err`, but `resp` will not be nil when there isn't an `err`.

I'd suggest
```
if err != nil {
  // handle err
} else if resp.StatusCode != http.StatusOK {
  // we can assume resp is not nil now, because that's idiomatic go
  // e.g. you can read http.Get documentation it will mention this. https://golang.org/pkg/net/http/#Client.Get
}

return nil
```
```

File: backend/src/apiserver/server/visualization_server_test.go (hunk 4 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server_test.go:180]: I assume what we want is: 
```
assert.Contains(t, err.Error(), "Internal Error: the visualization server host not exist")
```

File: backend/src/apiserver/server/visualization_server.go (hunk 6 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:119]: Good point, new revision of PR addressed the comment.

File: backend/src/apiserver/server/visualization_server.go [hunk 7]
```diff
@@ -115,13 +112,15 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
...
 }
 
-func isVisualizationServiceAlive(serviceURL string) bool {
+func isVisualizationServiceAlive(serviceURL string) error {
 	resp, err := http.Get(serviceURL)
+
 	if err != nil {
-		glog.Error("Unable to verify visualization service is alive!", err)
-		return false
+		return util.Wrap(err, "Internal Error: the visualization server host not exist!")
```
Comment (jingzhang36) [inline backend/src/apiserver/server/visualization_server.go:119]: could you both logging and returning the errors. Sometimes, when we debug, we also look up the log for details. So we probably should have the error reflected in both the returns and in the logs

Comment (jingzhang36) [reply backend/src/apiserver/server/visualization_server.go:119]: Other than that /lgtm

Comment (Bobgy) [reply backend/src/apiserver/server/visualization_server.go:119]: +1
and did you forget to update the error message?

File: backend/src/apiserver/server/visualization_server.go (hunk 3 above)
Comment (Bobgy) [reply backend/src/apiserver/server/visualization_server.go]: You can read documentation in https://golang.org/pkg/net/http/#Client.Get, the error can be other reasons, not just `server host not exist`.

File: backend/src/apiserver/server/visualization_server_test.go (hunk 4 above)
Comment (Bobgy) [reply backend/src/apiserver/server/visualization_server_test.go]: not really, please read: https://github.com/kubeflow/pipelines/pull/4201#discussion_r454789374

File: backend/src/apiserver/server/visualization_server.go (hunk 7 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:119]: Good points! Will fix in new revision of PR

File: backend/src/apiserver/server/visualization_server.go (hunk 3 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go]: Agree, we need to make `isVisualizationServiceAlive` generic, but make `TestGenerateVisualization_ServiceHostNotExistError` test restricted to ServiceNotExistError.

File: backend/src/apiserver/server/visualization_server.go [hunk 8]
```diff
@@ -115,13 +113,17 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
...
 
-func isVisualizationServiceAlive(serviceURL string) bool {
+func isVisualizationServiceAlive(serviceURL string) error {
 	resp, err := http.Get(serviceURL)
+
 	if err != nil {
-		glog.Error("Unable to verify visualization service is alive!", err)
-		return false
+		glog.Error(fmt.Sprintf("Unable to verify visualization service aliveness by sending request to %s and get error: %s", serviceURL, err.Error()))
+		return util.Wrap(err, fmt.Sprintf("Unable to verify visualization service aliveness by sending request to %s and get error: %s", serviceURL, err.Error()))
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:121]: nit: there is no need to encode err.Error() into the error message here, because util.Wrap did that for you.

File: backend/src/apiserver/server/visualization_server.go [hunk 9]
```diff
@@ -115,13 +113,17 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
...
 }
 
-func isVisualizationServiceAlive(serviceURL string) bool {
+func isVisualizationServiceAlive(serviceURL string) error {
 	resp, err := http.Get(serviceURL)
+
 	if err != nil {
-		glog.Error("Unable to verify visualization service is alive!", err)
-		return false
+		glog.Error(fmt.Sprintf("Unable to verify visualization service aliveness by sending request to %s and get error: %s", serviceURL, err.Error()))
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:120]: Also, you can probably reduce duplication by instantiating the error object first then glog the error object.

File: backend/src/apiserver/server/visualization_server_test.go [hunk 10]
```diff
@@ -155,7 +155,28 @@ func TestGenerateVisualization_ServiceNotAvailableError(t *testing.T) {
...
+		Type:      go_client.Visualization_ROC_CURVE,
+		Source:    "gs://ml-pipeline/roc/data.csv",
+		Arguments: "{}",
+	}
+	request := &go_client.CreateVisualizationRequest{
+		Visualization: visualization,
+	}
+	body, err := server.generateVisualizationFromRequest(request)
+	assert.Nil(t, body)
+	assert.Contains(t, err.Error(), "Unable to verify visualization service aliveness ")
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server_test.go:179]: nit: please also assert the wrapped error's error message is here

File: backend/src/apiserver/server/visualization_server.go [hunk 11]
```diff
@@ -78,11 +79,8 @@ func (s *VisualizationServer) validateCreateVisualizationRequest(request *go_cli
 // It returns the generated HTML as a string and any error that is encountered.
 func (s *VisualizationServer) generateVisualizationFromRequest(request *go_client.CreateVisualizationRequest) ([]byte, error) {
 	serviceURL := s.getVisualizationServiceURL(request)
-	if !isVisualizationServiceAlive(serviceURL) {
-		return nil, util.NewInternalServerError(
-			fmt.Errorf("service not available"),
-			"Service not available",
-		)
+	if err := isVisualizationServiceAlive(serviceURL); err != nil {
+		return nil, err
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:83]: nit: instead of returning err directly, suggest using util.Wrap on it.

The extra layer of error message provide more context.

It answers:
Why did we verify visualization server is alive?
It's because we are trying to generate a visualization.

File: backend/src/apiserver/server/visualization_server.go (hunk 8 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:121]: Right, but I'll leave `glog.Error()` with `err.Error()`. Let me know if you want to remove it too.

Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:121]: Fixed

File: backend/src/apiserver/server/visualization_server.go (hunk 9 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:120]: Fixed

File: backend/src/apiserver/server/visualization_server_test.go (hunk 10 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server_test.go:179]: Good point, fixed

File: backend/src/apiserver/server/visualization_server.go (hunk 11 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go:83]: Right, added one layer of `util.Wrap` on it.

File: backend/src/apiserver/server/visualization_server.go [hunk 12]
```diff
@@ -78,11 +79,8 @@ func (s *VisualizationServer) validateCreateVisualizationRequest(request *go_cli
 // It returns the generated HTML as a string and any error that is encountered.
 func (s *VisualizationServer) generateVisualizationFromRequest(request *go_client.CreateVisualizationRequest) ([]byte, error) {
 	serviceURL := s.getVisualizationServiceURL(request)
-	if !isVisualizationServiceAlive(serviceURL) {
-		return nil, util.NewInternalServerError(
-			fmt.Errorf("service not available"),
-			"Service not available",
-		)
+	if err := isVisualizationServiceAlive(serviceURL); err != nil {
+		return nil, util.Wrap(err, "Unable to verify visualization service aliveness.")
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:83]: nit: `return nil, util.Wrap(err, "Cannot generate visualization.")`

Because the internal error message is already telling it failed to verify service is alive.

File: backend/src/apiserver/server/visualization_server.go [hunk 13]
```diff
@@ -115,13 +113,17 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
...
 
-func isVisualizationServiceAlive(serviceURL string) bool {
+func isVisualizationServiceAlive(serviceURL string) error {
 	resp, err := http.Get(serviceURL)
+
 	if err != nil {
-		glog.Error("Unable to verify visualization service is alive!", err)
-		return false
+		glog.Error("Unable to verify visualization service aliveness ", err)
+		return util.Wrap(err, fmt.Sprintf("Unable to verify visualization service aliveness by sending request to %s", serviceURL))
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:121]: nit: for reducing duplication

My suggestion was
```
myError := util.Wrap(err, fmt.Sprintf("Unable to verify visualization service aliveness by sending request to %s", serviceURL))
glog.Error(myError)
return myError
```

File: backend/src/apiserver/server/visualization_server.go [hunk 14]
```diff
@@ -115,13 +113,17 @@ func (s *VisualizationServer) getVisualizationServiceURL(request *go_client.Crea
...
+	} else if resp.StatusCode != http.StatusOK {
+		glog.Error(fmt.Sprintf("Unable to verify visualization service aliveness by sending request to %s and get response code: %s !", serviceURL, resp.Status))
+		return errors.New(fmt.Sprintf("Unable to verify visualization service aliveness by sending request to %s and get response code: %s !", serviceURL, resp.Status))
```
Comment (Bobgy) [inline backend/src/apiserver/server/visualization_server.go:124]: same here using the pattern above

**Comment by PatrickXYS** [comment]
@Bobgy I think this is really a good chance to learn and get familiar with your conventions!

Don't worry about that will bother me, several rounds of review means that my code improves a lot.

File: backend/src/apiserver/server/visualization_server.go (hunk 12 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go]: Fixed.

File: backend/src/apiserver/server/visualization_server.go (hunk 13 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go]: Yeah I agree with your idea, fixed.

File: backend/src/apiserver/server/visualization_server.go (hunk 14 above)
Comment (PatrickXYS) [reply backend/src/apiserver/server/visualization_server.go]: Fixed.

**Comment by PatrickXYS** [comment]
Is there anyone have idea about why kubeflow-pipeline-back-test failed?

On my local, I have already ran `bazel build --action_env=PATH --define=grpc_no_ares=true //backend/src/apiserver/...` and it succeeded in all of the test cases.

From kubeflow-pipeline-back-test logs (https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4201/kubeflow-pipeline-backend-test/1283602125334515713), it only says server test failed without enough information.

```
FAIL: //backend/src/apiserver/server:go_default_test (see /root/.cache/bazel/_bazel_root/cae2d848e52acf5f1098083625f1beff/execroot/__main__/bazel-out/k8-fastbuild/testlogs/backend/src/apiserver/server/go_default_test/test.log)

Executed 18 out of 18 tests: 17 tests pass and 1 fails locally.
```

**Comment by Bobgy** [comment]
Not sure about why, https://github.com/kubeflow/pipelines/issues/3436 tracks the error logs not shown issue.

**Comment by Bobgy** [comment]
I'm asking @jingzhang36 if she can help with this.

**Comment by jingzhang36** [comment]
@PatrickXYS I checked out your pr and did a local bazel test. Below is the error message I got:

net/http.HandlerFunc.ServeHTTP
        GOROOT/src/net/http/server.go:1964
github.com/kubeflow/pipelines/backend/src/apiserver/server.TestUploadPipelineVersion_GetFromFileError
        backend/src/apiserver/server/pipeline_upload_server_test.go:425
testing.tRunner
        GOROOT/src/testing/testing.go:827
runtime.goexit
        GOROOT/src/runtime/asm_amd64.s:1333
E0716 04:57:23.239167   32328 pipeline_upload_server.go:160] Failed to upload pipelines. Error: Invalid pipeline version name.: Invalid input error: Pipeline name too long. Support maximum length of 100
E0716 04:57:23.250132   32328 run_metric_util.go:83] Internal error 'InternalServerError: Foo Error: test' when reporting metric 'node-1/metric-1'
E0716 04:57:23.474376   32328 visualization_server.go:125] Unable to verify visualization service aliveness by sending request to http://127.0.0.1:41485 and get response code: 500 Internal Server Error !
E0716 04:57:23.477673   32328 visualization_server.go:121] Unable to verify visualization service aliveness by sending request to http://127.0.0.2:53484: Get http://127.0.0.2:53484: dial tcp 127.0.0.2:53484: connect: connection refused
--- FAIL: TestGenerateVisualization_ServiceHostNotExistError (0.00s)
    visualization_server_test.go:181: 
                Error Trace:    visualization_server_test.go:181
                Error:          "Cannot generate visualization.: Unable to verify visualization service aliveness by sending request to http://127.0.0.2:53484: Get http://127.0.0.2:53484: dial tcp 127.0.0.2:53484: connect: connection refused" does not contain "dial tcp 127.0.0.2:53484: i/o timeout"
                Test:           TestGenerateVisualization_ServiceHostNotExistError
FAIL
================================================================================
Target //backend/src/apiserver/server:go_default_test up-to-date:
  bazel-bin/backend/src/apiserver/server/linux_amd64_stripped/go_default_test
INFO: Elapsed time: 1.161s, Critical Path: 0.76s
INFO: 2 processes: 2 processwrapper-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//backend/src/apiserver/server:go_default_test                           FAILED in 0.7s

**Comment by PatrickXYS** [comment]
@jingzhang36  Thanks for help.

It's kind of weird, on my local, the error msg should be like:

```
Cannot generate visualization.: Unable to verify visualization service aliveness by sending request to http://127.0.0.2:53484: Get "http://127.0.0.2:53484": dial tcp 127.0.0.2:53484: i/o timeout
```
Because the error message contains `dial tcp 127.0.0.2:53484: i/o timeout` and the test succeed.

Root-causing.

**Comment by PatrickXYS** [comment]
@Bobgy Can you take another look?

**Comment by Bobgy** [comment]
@PatrickXYS Thank you!
/lgtm
/approve
