### PR TITLE
fix: Delete the pipeline along with its all versions. Fixes #11665

### LINKED ISSUE #11665: [feature] Delete a pipeline and all its pipeline versions in one single step
### Feature Area

/area frontend

### What feature would you like to see?

Today when we try to delete a pipeline that has more than one version, we see the following error:

Image

It would be nice to be able to delete a pipeline and all its pipeline versions in one single step. For example, the message could be something like `This pipeline has more than one version. Deleting this pipeline will also delete all its versions. Are you sure you want to delete this pipeline and all its versions?`

### Is there a workaround currently?

Manually deleting all versions before deleting the pipeline is tedious and time consuming.

---

Love this idea? Give it a 👍.

### PR DESCRIPTION
**Pull request by milinddethe15**
fixes https://github.com/kubeflow/pipelines/issues/11665

**Description of your changes:**
* Adds a `cascade` parameter in `deletepipeline` API
* Handles delete dialog based on pipeline along with its versions
* Fixes error while deleting pipeline containing versions

Follow up PR based on: https://github.com/kubeflow/pipelines/pull/11745

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by milinddethe15** [comment]
https://github.com/user-attachments/assets/294ac1df-5222-48c4-8d31-7603b60247d0

File: backend/src/apiserver/resource/resource_manager.go [hunk 1]
```diff
@@ -298,20 +298,45 @@ func (r *ResourceManager) GetPipelineByNameAndNamespaceV1(name string, namespace
...
+			err = r.pipelineStore.UpdatePipelineVersionStatus(pipelineVersion.UUID, model.PipelineVersionDeleting)
+			if err != nil {
+				return util.Wrapf(err, "Failed to change the status of pipeline version id %v to DELETING during cascade delete", pipelineVersion.UUID)
+			}
+
+			// Delete the pipeline version from the database
+			err = r.pipelineStore.DeletePipelineVersion(pipelineVersion.UUID)
+			if err != nil {
+				return util.Wrapf(err, "Failed to delete pipeline version %v during cascade delete of pipeline %v", pipelineVersion.UUID, pipelineId)
+			}
```
Comment (hbelmiro) [inline backend/src/apiserver/resource/resource_manager.go:330]: It would be nice to log an info message in the logs informing that the version was deleted.

**Review by hbelmiro — APPROVED** [review]
/lgtm

@HumairAK can you PTAL?

**Review by droctothorpe — APPROVED** [review]
This contribution is thorough, comprehensive, and touches so much of the codebase, @milinddethe15. Kudos and thank you! Approved.

**Comment by hbelmiro** [comment]
> This contribution is thorough, comprehensive, and touches so much of the codebase, @milinddethe15. Kudos and thank you! Approved.

@droctothorpe, it looks like the GitHub UI approval no longer adds the `approved` label.
Can you please approve it with the `/approve` comment?

**Comment by juliusvonkohout** [comment]
Thank you @milinddethe15
