### PR TITLE
fix(frontend): Fix run comparison filter

### LINKED ISSUE #7827: [frontend] Run Comparison filter mechanism broken
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?

Kubeflow Pipelines Standalone

*  KFP version: 

2.0.0-alpha.2

### Steps to reproduce

1. Go to the "Runs" tab on KFP
2. Select at least two runs, and click "Compare runs"
3. Type something into the "Filter runs" field which should filter out the runs by "Run name"

### Expected result

You should see the runs filter by their "Run name" (as they do on the "Runs" tab), but nothing changes.

### Materials and Reference

The below video shows how the filter mechanism works on the "Runs" tab, but does not work on the Run Comparison page.

https://user-images.githubusercontent.com/7987279/171753804-2493547e-7f9a-41ca-a04d-3bcfa6e3d74f.mp4

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by zpChris**
**Description of your changes:**
- Fix #7827 

1. Add filter functionality for run lists with a run ID list mask
2. Add tests to verify that the filter mechanism for `RunList.tsx` works correctly in all cases

**Screen Recording:**

_This screencast shows both the "Runs" tab and the Run Comparison page working correctly (though only the latter needed a fix)._

https://user-images.githubusercontent.com/7987279/171758270-80080e81-4df8-4bf0-804d-8db4a5d61e8b.mp4

**Notes:**
- This issue occurred because the filtering mechanism typically occurs through the [`listRuns` API](https://github.com/kubeflow/pipelines/blob/340318625c527836af1c9abc0fd0d76c0a466333/frontend/src/apis/run/api.ts#L1725), but since that method does not have support for the `runIdListMask`, when a mask exists each run is fetched individually (see the [`_loadRuns`](https://github.com/kubeflow/pipelines/blob/0cf817364cc7b3156ea4b4e16fee3f193d8a6744/frontend/src/pages/RunList.tsx#L328-L337) method). This individual fetching of runs did not have a filtering mechanism, and I added that in this PR.
- Currently, only the ["name substring"](https://github.com/kubeflow/pipelines/blob/340318625c527836af1c9abc0fd0d76c0a466333/frontend/src/components/CustomTable.tsx#L519-L531) filtering is supported, so I have hard-coded the `filterSubstring` within `RunList.tsx` to detect and apply this filter. However, if more filter options are added in the future, we will likely want to separate this filter logic out.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: frontend/src/pages/RunList.tsx [hunk 1]
```diff
@@ -429,14 +432,27 @@ class RunList extends React.PureComponent<RunListProps, RunListState> {
...
     return Promise.all(
       displayRuns.map(async displayRun => {
         let getRunResponse: ApiRunDetail;
         try {
           getRunResponse = await Apis.runServiceApi.getRun(displayRun.run!.id!);
-          displayRun.run = getRunResponse.run!;
+          if (getRunResponse.run?.name?.toLowerCase().includes(filterSubstring)) {
+            displayRun.run = getRunResponse.run!;
+          } else {
+            displayRuns.splice(displayRuns.indexOf(displayRun), 1);
```
Comment (zpChris) [inline frontend/src/pages/RunList.tsx:454]: This may be an unconventional approach to filter out unwanted elements (typically a new array with only the desired elements would be created), but I wanted to maintain both the orders of the runs and the parallel asynchronous `getRun` requests, and thought this outweighed the larger `O(n)` delay for removing each element. This is especially because the `runIdListMask` means that the array will likely be small (in the case of the `Compare.tsx` page, a maximum of 10 runs). However, I can change this approach if the readability is poor.

File: frontend/src/pages/RunList.tsx [hunk 2]
```diff
@@ -331,9 +331,12 @@ class RunList extends React.PureComponent<RunListProps, RunListState> {
...
       displayRuns = this.props.runIdListMask.map(id => ({ run: { id } }));
-      // listRuns doesn't currently support batching by IDs, so in this case we retrieve each run
-      // individually.
-      await this._getAndSetRuns(displayRuns);
+      const filter = JSON.parse(
+        decodeURIComponent(request.filter || '{"predicates": []}'),
+      ) as ApiFilter;
+      // listRuns doesn't currently support batching by IDs, so in this case we retrieve and filter
+      // each run individually.
+      await this._getAndSetRuns(displayRuns, filter);
```
Comment (zijianjoy) [inline frontend/src/pages/RunList.tsx:339]: displayRuns = this.props.runIdListMask.map(id => ({ run: { id } }));
      await this._getAndSetRuns(displayRuns);

      const filter = JSON.parse(
        decodeURIComponent(request.filter || '{"predicates": []}'),
      ) as ApiFilter;
      const predicates = filter.predicates?.filter(p => p.key === 'name' && p.op === PredicateOp.ISSUBSTRING);
      const substrings = predicates?.map(p => p.string_value?.toLowerCase() || '');
      displayRuns = displayRuns.filter(runDetail => {
        for (let sub in substrings) {
          if (!(runDetail?.run?.name?.toLowerCase().includes(sub))) {
            return false;
          }
        }
        return true;
      });

How do you think about this logic? To explain:
1. Fetch all run details first.
2. Convert filter predicates to a list of `substrings`.
3. For each run's name, check whether it contains substrings. If not, remove this run from `displayRuns` list.

File: frontend/src/pages/RunList.tsx [hunk 3]
```diff
@@ -429,14 +432,27 @@ class RunList extends React.PureComponent<RunListProps, RunListState> {
...
-  private _getAndSetRuns(displayRuns: DisplayRun[]): Promise<DisplayRun[]> {
+  private _getAndSetRuns(displayRuns: DisplayRun[], filter: ApiFilter): Promise<DisplayRun[]> {
+    const filterSubstring =
+      filter.predicates &&
+      filter.predicates[0] &&
+      filter.predicates[0].key === 'name' &&
+      filter.predicates[0].op === PredicateOp.ISSUBSTRING &&
+      filter.predicates[0].string_value
+        ? filter.predicates[0].string_value.toLowerCase()
+        : '';
```
[the remark this answers is not in the document]
Comment (zpChris) [reply frontend/src/pages/RunList.tsx:445]: Ok, that makes sense I'll make that change. 👍

File: frontend/src/pages/RunList.tsx (hunk 2 above)
Comment (zpChris) [reply frontend/src/pages/RunList.tsx]: That makes sense; I didn't realize that there could be multiple predicates checking substrings against the same value, this solution works much better in that case. I added another test to check this behavior.

I updated the `for` loop line to `for (const sub of substrings) {` since the `sub` value is never reassigned and the `for...of` loop is used for arrays.

Comment (zijianjoy) [reply frontend/src/pages/RunList.tsx]: Make sense on the use of `const`! You can find definition of filter in `filter.proto`. And even more, this file describes advanced usage like IN: https://github.com/kubeflow/pipelines/blob/master/backend/api/filter.proto#L106-L117. But since frontend is not creating IN filter, we simplify the logic by only considering `ISSUBSTRING` predicateOp

File: frontend/src/pages/RunList.test.tsx [hunk 4]
```diff
@@ -381,6 +381,50 @@ describe('RunList', () => {
     expect(Apis.runServiceApi.getRun).toHaveBeenCalledWith('run2');
   });
 
+  it('loads given and filtered list of runs only', async () => {
+    mockNRuns(5, {});
+    const props = generateProps();
+    props.runIdListMask = ['filterRun1', 'filterRun2', 'notincluded'];
+    tree = shallow(<RunList {...props} />);
+    await (tree.instance() as RunListTest)._loadRuns({
```
[the remark this answers is not in the document]
Comment (zpChris) [reply frontend/src/pages/RunList.test.tsx:389]: Got it ok, I'll note that for the future - thank you!

File: frontend/src/pages/RunList.tsx (hunk 1 above)
Comment (zpChris) [reply frontend/src/pages/RunList.tsx]: Resolving this comment as this code is now outdated, as we decided to use the `filter` function instead.
