### PR TITLE
fix(frontend); make cluster domain configurable for TensorBoard

### LINKED ISSUE #12785: [frontend] Hard-coded cluster.local breaks TensorBoard in custom DNS environments
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
*  Installed via official docs: https://www.kubeflow.org/docs/components/pipelines/operator-guides/installation/
   Tested on: Kubernetes clusters with custom cluster domain (e.g., `cluster.corp`)
* KFP version: 2.14.3
* KFP SDK version: N/A (frontend server issue)

### Steps to reproduce
1. Deploy Kubeflow Pipelines on a Kubernetes cluster configured with a **custom cluster domain** (not the default `cluster.local`)
2. Run a pipeline that generates TensorBoard logs
3. Click "Open TensorBoard" from the Pipelines UI
4. TensorBoard fails to connect
The frontend server constructs the TensorBoard URL with a hard-coded `cluster.local`:

  **File**: [frontend/server/k8s-helper.ts (line 170)](https://github.com/kubeflow/pipelines/blob/master/frontend/server/k8s-helper.ts#L170)

 
`const address = http://${viewer.metadata.name}-service.${namespace}.svc.cluster.local:80/tensorboard/${viewer.metadata.name}/`;

In clusters using custom domains, this causes DNS resolution to fail.
### Expected result
The cluster domain should be configurable via the CLUSTER_DOMAIN environment variable. TensorBoard should work in any Kubernetes cluster regardless of its DNS configuration.

### Materials and Reference

- Affected file: [frontend/server/k8s-helper.ts (line 170)](https://github.com/kubeflow/pipelines/blob/master/frontend/server/k8s-helper.ts#L170)
- I will try to raise a PR to fix this issue.

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by Priyanshu-u07**
**Description of your changes:**

This PR removes the hard-coded `cluster.local` value for TensorBoard service addresses and makes the cluster domain configurable using the `CLUSTER_DOMAIN` environment variable. It also makes the object store service name configurable via the `OBJECT_STORE_HOST` environment variable, resolving CI DNS failures by providing a flexible way to point to the correct artifact storage host (defaulting to `seaweedfs`).

**Key improvements:**

- Configurable Domain: Adds `CLUSTER_DOMAIN` support to frontend and service layers.
- Configurable Service Host: Adds `OBJECT_STORE_HOST` support to the profile controller (sync.py) and deployment manifests to allow custom naming for artifact storage.
- Auto-Fallback:  Defaults to `cluster.local` and `seaweedfs` respectively to prevent breaking existing setups.
- Manifest Integration: Automatically pulls configuration from the shared ConfigMap.

This allows Kubeflow Pipelines to work correctly on Kubernetes clusters that use a non-default DNS domain (e.g., `cluster.corp`, `k8s.internal`).

**Related Fix**: This PR adds the frontend support for the custom cluster domain. Fix already implemented in the backend (#12701).

- Resolves CI DNS failures in multi-user E2E tests.

Fixes #12785 

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: frontend/server/k8s-helper.ts [hunk 1]
```diff
@@ -146,6 +149,7 @@ export async function newTensorboardInstance(
 export async function getTensorboardInstance(
   logdir: string,
   namespace: string,
```
Comment (jeffspahr) [inline frontend/server/k8s-helper.ts:152]: **Bug:** The backend PR #12701 (`metadata_helpers.py:36`) defaults `CLUSTER_DOMAIN` to `.svc.cluster.local` (with the `.svc.` prefix), but here you hardcode `.svc.` in the template and default `CLUSTER_DOMAIN` to `cluster.local` (without the prefix).

This means the same env var has different expected formats in the backend vs frontend. An operator cannot set a single value that works for both.

Either:
- Change this PR to match the backend convention (default to `.svc.cluster.local`, drop the hardcoded `.svc.` from the template), or
- Change the backend to match this PR's convention

The former is probably safer since #12701 is already merged.

File: frontend/server/handlers/tensorboard.ts [hunk 2]
```diff
@@ -57,7 +57,13 @@ export const getTensorboardHandlers = (
...
+      res.send(
+        await k8sHelper.getTensorboardInstance(
+          logdir as string,
+          namespace as string,
+          tensorboardConfig.clusterDomain,
+        ),
+      );
     } catch (err) {
       const details = await parseError(err);
       console.error(`Failed to list Tensorboard pods: ${details.message}`, details.additionalInfo);
```
Comment (jeffspahr) [inline frontend/server/handlers/tensorboard.ts:69]: **Bug:** `clusterDomain` is passed to `getTensorboardInstance` here (the `get` handler), but `waitForTensorboardInstance` (called in the `create` handler at line 127) and `deleteTensorboardInstance` (called in the `delete` handler at line 168) both call `getTensorboardInstance` internally **without** passing `clusterDomain`. They will always use the default `cluster.local`.

Both `waitForTensorboardInstance` and `deleteTensorboardInstance` need the same `clusterDomain` parameter threaded through, and the `create`/`delete` handlers need to pass it.

**Comment by Priyanshu-u07** [comment]
Hi @jeffspahr,
I have updated the PR based on your comment and all CI checks are passing now. Would appreciate another review when you get a chance. Thanks

File: frontend/server/k8s-helper.ts [hunk 3]
```diff
@@ -165,12 +170,17 @@ export async function getTensorboardInstance(
       // but if there is a hash collision, not check logdir will return error tensorboard link
       // if check logdir and then create Viewer CRD with same name will break anyway.
       // TODO fix hash collision
-      (viewer: any) => {
+      (response: any) => {
+        const viewer = response.body || response;
```
Comment (jeffspahr) [inline frontend/server/k8s-helper.ts]: **Behavioral change unrelated to feature:** The original code accesses `viewer.body.spec` and `viewer.body.metadata.name` directly. This PR changes the unpacking to `response.body || response` then accesses `viewer.spec` / `viewer.metadata.name`.

This silently changes how the K8s client response object is parsed. The existing code on `master` (line 169) uses `viewer.body.spec` and it works, so the old shape was correct for the current client library version.

If this fixes a real issue (e.g., a client library version change), it should be called out in the PR description and ideally in its own commit. If not, it risks breaking the existing flow. Please justify this change or revert it.

File: manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py [hunk 4]
```diff
@@ -91,9 +96,10 @@ def server_factory(frontend_image,
                    frontend_tag,
                    disable_istio_sidecar,
                    artifacts_proxy_enabled,
-                   artifact_retention_days,
-                   url="",
-                   controller_port=8080):
+                    artifact_retention_days,
```
Comment (jeffspahr) [inline manifests/kustomize/base/installs/multi-user/pipelines-profile-controller/sync.py]: `cluster_domain` is a required positional parameter with no default, unlike every other parameter in this function. If any caller invokes `server_factory` without it, they will get a `TypeError`. Add a default for safety and consistency:

```python
cluster_domain=".svc.cluster.local",
```

**Comment by Priyanshu-u07** [comment]
Hi @jeffspahr 
All CI checks are passing now. Please review when you get a chance.

**Comment by jeffspahr** [comment]
lgtm @Priyanshu-u07! 

@droctothorpe this is good to merge when you get a chance.

**Comment by Priyanshu-u07** [comment]
updated the PR description and style nits.
@droctothorpe could you approve and merge when get a chance?

**Comment by droctothorpe** [comment]
/lgtm
/approve

Thank you for the contribution, @Priyanshu-u07, and thank you for the reviews, @jeffspahr! 🙏
