### PR TITLE
fix(backend): Read env var for default service account in multi-user mode. Fix #7336

### LINKED ISSUE #7336: [backend] Use `default-editor` as serviceAccountName in multi-user mode
### Environment

This is an issue I found with KFP backend 1.8.0 on Full fledged Kubeflow. 

### Steps to reproduce

Run a KFP pipeline on full Kubeflow, the error is 

```
This step is in Error state with this message: task 'conditional-execution-pipeline-with-exit-handler-6gfkq.exit-handler-1.flip-coin-op' errored: pods "conditional-execution-pipeline-with-exit-handler-6gfkq-1717566668" is forbidden: error looking up service account jamxl/pipeline-runner: serviceaccount "pipeline-runner" not found
```

### Materials and Reference

We are always using the `pipeline-runner` service account in this file: https://github.com/kubeflow/pipelines/blob/3e734ed19146f569e910f75627d12239ec2e86dc/backend/src/apiserver/template/template.go#L191-L202. 

Instead, it should use `default-editor` for multi-user mode, the util to check multi-user mode is https://github.com/kubeflow/pipelines/blob/2e945750cb1758eea6db8453b437e57e68152b4a/backend/src/apiserver/common/config.go#L94

---

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by zijianjoy**
**Description of your changes:**
Fix #7336

Due to the change in https://github.com/kubeflow/pipelines/pull/6689/files#diff-2bc2047e64f4bb524fb40748997d97f0c96c1c8884a87c81ffa3a7177f8cf0f1R195-R206, we cannot use the env var `DefaultPipelineRunnerServiceAccount` to set service account in multi-user mode. It is because the previous change will try to read a env var flag `pipeline-runner` instead of `DefaultPipelineRunnerServiceAccount` as this is deleted: https://github.com/kubeflow/pipelines/pull/6689/files#diff-47d6ab6bca869e0559465170316707ceda42f65103bd0d4e93519294305e62d1. But we should keep the flag.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by chensun** [comment]
Thank you for the fix, @zijianjoy !

Looks like you need to update the test as well?
```
=== RUN   TestCreateRun_Multiuser
    run_server_test.go:247: 
        	Error Trace:	run_server_test.go:247
        	Error:      	Not equal: 
        	            	expected: go_client.RunDetail{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), Run:(*go_client.Run)(0xc0002a2e00), PipelineRuntime:(*go_client.PipelineRuntime)(0xc000c8f680)}
        	            	actual  : go_client.RunDetail{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), Run:(*go_client.Run)(0xc0002a2d20), PipelineRuntime:(*go_client.PipelineRuntime)(0xc000c8f4f0)}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -95,3 +95,3 @@
        	            	   },
        	            	-  ServiceAccount: (string) (len=14) "default-editor",
        	            	+  ServiceAccount: (string) (len=15) "pipeline-runner",
        	            	   CreatedAt: (*timestamppb.Timestamp)({
        	            	@@ -158,3 +158,3 @@
        	            	   PipelineManifest: (string) "",
        	            	-  WorkflowManifest: (string) (len=839) "{\"kind\":\"Workflow\",\"apiVersion\":\"argoproj.io/v1alpha1\",\"metadata\":{\"name\":\"workflow-name\",\"namespace\":\"ns1\",\"uid\":\"workflow1\",\"creationTimestamp\":null,\"labels\":{\"pipeline/runid\":\"123e4567-e89b-12d3-a456-426655440000\"},\"annotations\":{\"pipelines.kubeflow.org/run_name\":\"run1\"}},\"spec\":{\"templates\":[{\"name\":\"testy\",\"inputs\":{},\"outputs\":{},\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"false\"},\"labels\":{\"pipelines.kubeflow.org/cache_enabled\":\"true\"}},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay\",\"command\":[\"cowsay\"],\"args\":[\"hello world\"],\"resources\":{}}}],\"entrypoint\":\"testy\",\"arguments\":{\"parameters\":[{\"name\":\"param1\",\"value\":\"world\"}]},\"serviceAccountName\":\"default-editor\",\"podMetadata\":{\"labels\":{\"pipeline/runid\":\"123e4567-e89b-12d3-a456-426655440000\"}}},\"status\":{\"phase\":\"Running\",\"startedAt\":null,\"finishedAt\":null}}"
        	            	+  WorkflowManifest: (string) (len=840) "{\"kind\":\"Workflow\",\"apiVersion\":\"argoproj.io/v1alpha1\",\"metadata\":{\"name\":\"workflow-name\",\"namespace\":\"ns1\",\"uid\":\"workflow1\",\"creationTimestamp\":null,\"labels\":{\"pipeline/runid\":\"123e4567-e89b-12d3-a456-426655440000\"},\"annotations\":{\"pipelines.kubeflow.org/run_name\":\"run1\"}},\"spec\":{\"templates\":[{\"name\":\"testy\",\"inputs\":{},\"outputs\":{},\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"false\"},\"labels\":{\"pipelines.kubeflow.org/cache_enabled\":\"true\"}},\"container\":{\"name\":\"\",\"image\":\"docker/whalesay\",\"command\":[\"cowsay\"],\"args\":[\"hello world\"],\"resources\":{}}}],\"entrypoint\":\"testy\",\"arguments\":{\"parameters\":[{\"name\":\"param1\",\"value\":\"world\"}]},\"serviceAccountName\":\"pipeline-runner\",\"podMetadata\":{\"labels\":{\"pipeline/runid\":\"123e4567-e89b-12d3-a456-426655440000\"}}},\"status\":{\"phase\":\"Running\",\"startedAt\":null,\"finishedAt\":null}}"
        	            	  })
        	Test:       	TestCreateRun_Multiuser
--- FAIL: TestCreateRun_Multiuser (0.01s)
```

**Comment by zijianjoy** [comment]
Thank you @chensun and @Bobgy ! I have resolved the test issue.

File: backend/src/apiserver/common/config.go [hunk 1]
```diff
@@ -23,14 +23,15 @@ import (
...
-	CacheEnabled                        string = "CacheEnabled"
-	KubeflowUserIDHeader                string = "KUBEFLOW_USERID_HEADER"
-	KubeflowUserIDPrefix                string = "KUBEFLOW_USERID_PREFIX"
-	UpdatePipelineVersionByDefault      string = "AUTO_UPDATE_PIPELINE_DEFAULT_VERSION"
-	TokenReviewAudience                 string = "TOKEN_REVIEW_AUDIENCE"
+	MultiUserMode                           string = "MULTIUSER"
+	MultiUserModeSharedReadAccess           string = "MULTIUSER_SHARED_READ"
+	PodNamespace                            string = "POD_NAMESPACE"
+	CacheEnabled                            string = "CacheEnabled"
+	DefaultPipelineRunnerServiceAccountFlag string = "DEFAULTPIPELINERUNNERSERVICEACCOUNT"
```
Comment (chensun) [inline backend/src/apiserver/common/config.go:30]: nit: For the naming of both the constant variable and the key/flag used in config.json, do you think we need to carry `Default` as a prefix? 
How about just `PipelineRunnerServiceAccountFlag string = "PIPELINE_RUNNER_SERVICE_ACCOUNT"` or `PipelineRunnerServiceAccountKey string = "PIPELINE_RUNNER_SERVICE_ACCOUNT"`?

File: backend/src/apiserver/config/config.json [hunk 2]
```diff
@@ -15,7 +15,7 @@
   "ARCHIVE_CONFIG_LOG_FILE_NAME": "main.log",
   "ARCHIVE_CONFIG_LOG_PATH_PREFIX": "/artifacts",
   "InitConnectionTimeout": "6m",
-  "DefaultPipelineRunnerServiceAccount": "pipeline-runner",
+  "DEFAULTPIPELINERUNNERSERVICEACCOUNT": "pipeline-runner",
```
Comment (chensun) [inline backend/src/apiserver/config/config.json:18]: nit: use either camel case or upper case with underscores, otherwise this is pretty hard to read.
(ideally we should be consistent on the naming, not sure which one is more conventional though)

File: backend/src/apiserver/common/config.go (hunk 1 above)
Comment (Bobgy) [reply backend/src/apiserver/common/config.go:30]: To explain why it had the default prefix: because users can also specify service account when creating runs. The env var is the default.

+1 for changing the name to make it more readable. Ideally, when we change the name, also read from the legacy env var as fallback.

Comment (zijianjoy) [reply backend/src/apiserver/common/config.go:30]: I think we need to set the default prefix because user can override service account when creating Pipeline Run. https://screenshot.googleplex.com/AApqJMAg7ikYpnZ.

More importantly, changing the env var name is going to be a breaking change as Kubeflow manifests and All distributions rely on the existing name. (Note: We are not creating a new variable, I am only bringing back the old variable that was removed accidentally in this file https://github.com/kubeflow/pipelines/pull/6689/files#diff-47d6ab6bca869e0559465170316707ceda42f65103bd0d4e93519294305e62d1)

See: https://github.com/kubeflow/pipelines/blob/74c7773ca40decfd0d4ed40dc93a6af591bbc190/manifests/kustomize/base/installs/multi-user/api-service/params.env

File: backend/src/apiserver/config/config.json (hunk 2 above)
Comment (zijianjoy) [reply backend/src/apiserver/config/config.json:18]: I agree that we should use `upper case with underscore`. But again, it is a breaking change that I don't want to introduce right now. Community has been testing Kubeflow v1.5 using KFP 1.8.0, if we are going to make this breaking change, we should aim for next release.

File: backend/src/apiserver/common/config.go (hunk 1 above)
Comment (chensun) [reply backend/src/apiserver/common/config.go:30]: I think all configs are meant for default and overridable, thus the prefix "Default" is redundant.
But I see your point about avoiding breaking changes. SGTM.

File: backend/src/apiserver/config/config.json (hunk 2 above)
Comment (chensun) [reply backend/src/apiserver/config/config.json:18]: Okay, that's reasonable.

**Review by chensun — COMMENTED** [review]
/lgtm
/approve

Thanks!
