### PR TITLE
Fixes deletion of recurring runs

### LINKED ISSUE #1181: Bug: Unable to delete recurring run configs in UI
I currently have an experiment with a few recurring runs configured:

image

If I try to delete one, I get the success message, but also an error popup saying that the delete operation failed

image

For people searching, the error message is:
> #### Failed to delete recurring run config
> Failed to delete recurring run config: <config_id> with error: "Cannot read property 'configuration' of undefined"

This happens on both first and subsequent tries to delete recurring runs.

After the failed deletion attempt, the pipeline is still running on schedule, so I can confirm that it has in fact not been deleted:

image

I'm on Kubeflow 0.5.0 on GKE.

### PR DESCRIPTION
**Pull request by rileyjbauer**
Also redirects after deleting pipeline from pipeline details page.

Fixes #1181

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/1185)

### CODE REVIEW

File: frontend/src/lib/Buttons.ts [hunk 1]
```diff
@@ -80,11 +80,12 @@ export default class Buttons {
   }
 
   public delete(getSelectedIds: () => string[], resourceName: 'pipeline' | 'recurring run config',
-    callback: (selectedIds: string[], success: boolean) => void, useCurrentResource: boolean): ToolbarActionConfig {
+    callback: (selectedIds: string[], success: boolean) => void, useCurrentResource: boolean,
+    refreshOnComplete: boolean): ToolbarActionConfig {
```
Comment (yebrahim) [inline frontend/src/lib/Buttons.ts]: Isn't this always desired? If it is, we can just always call it here.
If it isn't, why can't refresh be optionally called by the callsite as part of the callback?

File: frontend/src/pages/PipelineDetails.tsx [hunk 2]
```diff
@@ -131,8 +131,13 @@ class PipelineDetails extends Page<{}, PipelineDetailsState> {
...
       actions = actions.concat([
         buttons.newExperiment(() => this.state.pipeline ? this.state.pipeline.id! : ''),
-        buttons.delete(() => this.state.pipeline ? [this.state.pipeline.id!] : [],
-          'pipeline', () => null, true),
+        buttons.delete(
+          () => this.state.pipeline ? [this.state.pipeline.id!] : [],
+          'pipeline',
+          this._deleteCallback.bind(this),
+          true, /* useCurrentResource */
+          false, /* refreshOnComplete */
```
Comment (yebrahim) [inline frontend/src/pages/PipelineDetails.tsx]: If there's a good reason why we don't refresh after delete, it's worth calling it out in a comment here.

File: frontend/src/lib/Buttons.ts (hunk 1 above)
Comment (rileyjbauer) [reply frontend/src/lib/Buttons.ts]: It isn't desirable when you're on a specific resource's page (e.g. Run Details), and you delete that resource. In that case, a request is sent to the server to reload the page for a resource that no longer exists before redirecting to whatever page you actually want to be on.

The second part/suggestion would work. My thinking was just that this would prevent duplicate code in the callbacks

File: frontend/src/pages/PipelineDetails.tsx (hunk 2 above)
Comment (rileyjbauer) [reply frontend/src/pages/PipelineDetails.tsx]: Done

File: frontend/src/lib/Buttons.ts (hunk 1 above)
Comment (yebrahim) [reply frontend/src/lib/Buttons.ts]: Why not use the `useCurrentResource` flag then? Seems like it has the same information.

Comment (rileyjbauer) [reply frontend/src/lib/Buttons.ts]: No strong opinion here. I thought maybe it would be useful to have an explicit flag so that the implications are clear, but there's no reason AFAICT that we couldn't use the `useCurrentResource` (or situation where that wouldn't make sense at the moment).

I can change it if you think it's better to not add the extra flag

Comment (yebrahim) [reply frontend/src/lib/Buttons.ts]: I think it's a generally good idea to simplify the interface provided the caller doesn't need to know this flag is used for two different things. It seems internal to the method's implementation.

Comment (rileyjbauer) [reply frontend/src/lib/Buttons.ts]: Sounds good. It's been removed
