### PR TITLE
fix(backend): Fix "Unknown execution spec" error. Fixes #8256

### LINKED ISSUE #8256: [bug] Pipeline metrics Invalid input error: Unknown execution spec
### Environment

*  How do you deploy Kubeflow Pipelines (KFP)?
    Kubeflow/manifest  v1.6 
    AKS v1.22 

*  KFP version:  ml-pipeline/api-server:2.0.0-alpha.3

*  KFP SDK version: '1.8.13'

### Steps to reproduce

```
from kfp.components import InputPath, OutputPath, create_component_from_func
from kfp import dsl
def produce_metrics(
  # Note when the `create_component_from_func` method converts the function to a component, the function parameter "mlpipeline_metrics_path" becomes an output with name "mlpipeline_metrics" which is the correct name for metrics output.
  mlpipeline_metrics_path: OutputPath('Metrics'),
):
    import json

    accuracy = 0.1
    metrics = {
    'metrics': [{
      'name': 'accuracy-score', # The name of the metric. Visualized as the column name in the runs table.
      'numberValue':  accuracy, # The value of the metric. Must be a numeric value.
      'format': "PERCENTAGE",   # The optional format of the metric. Supported values are "RAW" (displayed in raw format) and "PERCENTAGE" (displayed in percentage format).
    }]
    }
    with open(mlpipeline_metrics_path, 'w') as f:
        json.dump(metrics, f)

produce_metrics_op = create_component_from_func(
    produce_metrics,
    base_image='python:3.7',
    packages_to_install=[],
    output_component_file='component.yaml',
)
from kfp import dsl
import os, kfp
@dsl.pipeline(
    name='KF iris PoC',
    description='Simple TF'
)
def test():
     task=produce_metrics_op()
import os,kfp
with open(os.environ['KF_PIPELINES_SA_TOKEN_PATH'], "r") as f:
    TOKEN = f.read()
client = kfp.Client(host='http://ml-pipeline.kubeflow.svc.cluster.local:8888',existing_token=TOKEN) 

client.create_run_from_pipeline_func(
    test,
    mode=kfp.dsl.PipelineExecutionMode.V1_LEGACY,
    arguments={}
   
)
```
### Expected result
image

### Materials and reference
https://www.kubeflow.org/docs/components/pipelines/sdk/pipelines-metrics/

I cannot see the pipeline metrics in the UI but the pipeline artifact is logged i am getting this error in ml-pipeline
```
I0912 09:12:02.846997       8 error.go:259] Invalid input error: Unknown execution spec
InternalServerError: failed to unmarshal workflow
```
image

### Labels

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by chensun**
**Description of your changes:**
Fixes https://github.com/kubeflow/pipelines/issues/8256
Manually verified the change resolves the aforementioned issue:
image

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: backend/src/apiserver/resource/resource_manager.go [hunk 1]
```diff
@@ -1124,7 +1124,7 @@ func (r *ResourceManager) ReadArtifact(runID string, nodeID string, artifactName
 	if run.WorkflowRuntimeManifest == "" {
 		return nil, util.NewInvalidInputError("read artifact from run with v2 IR spec is not supported")
 	}
-	execSpec, err := util.NewExecutionSpec([]byte(run.WorkflowRuntimeManifest))
```
Comment (yhwang) [inline backend/src/apiserver/resource/resource_manager.go:1127]: nice catch and this is the only place that calls `NewExecutionSpec()` which assumes the content is YAML. The content is in JSON format. sorry that I didn't catch the bug when doing the abstraction interface.

Comment (yhwang) [reply backend/src/apiserver/resource/resource_manager.go:1127]: /lgtm

Comment (yhwang) [reply backend/src/apiserver/resource/resource_manager.go:1127]: there is a `TestReadArtifact_Succeed` test case and it doesn't fail. I guess the testing data can pass the `yaml.Unmarshal` magically. thinking if we can update the test case to catch up with this kind of error. I can work on that.

Comment (chensun) [reply backend/src/apiserver/resource/resource_manager.go:1127]: > which assumes the content is YAML. The content is in JSON format

I had the impression that because YAML is a superset of JSON, normally YAML serialization/deserialization libraries can handle both YAML and JSON (Didn't check if that's the case here, I probably got this impression from some Python library)

> there is a TestReadArtifact_Succeed test case and it doesn't fail.

I noticed the test as well. I think in my debugging of KFP runtime, `run.WorkflowRuntimeManifest` at this point doesn't carry the `TypeMeta` part. It was unclear to me that if it should at this point, or maybe the type needs to be told (by passing `util.ArgoWorkflow`) like the rest `NewExeuctionSpec*` calls. The latter seems making sense to me.

**Comment by chensun** [comment]
Merging this to unblock the release.

/approve

File: backend/src/apiserver/resource/resource_manager.go (hunk 1 above)
Comment (yhwang) [reply backend/src/apiserver/resource/resource_manager.go:1127]: yea, I would say it should carry `TypeMeta` and also specify `util.ArgoWorkflow`. at least so far we haven't supported dynamically switching orchestration engine yet :-p

**Comment by yhwang** [comment]
@chensun just want to update you on one doubt we had earlier:
> run.WorkflowRuntimeManifest at this point doesn't carry the TypeMeta part. It was unclear to me that if it should at this point, or maybe the type needs to be told (by passing util.ArgoWorkflow) like the rest NewExeuctionSpec* calls. 

It's from persistence agent. Somehow, the `Workflow` CRs retrieved from Argo WorkflowInformer don't have TypeMeta. I don't think we should fill in that information manually. But that's what it is. Just need to be aware not to use `NewExecutionSpec()` if there is no TypeMeta.
