### PR TITLE
fix(backend): resolve IfPresent conditions in component.yaml. Fixes #11009

### LINKED ISSUE #11009: [backend] conditions in component.yaml does not work properly
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow Platform (EKS)
*  KFP version: 
v2.2.0
*  KFP SDK version: 
v2.8.0

### Steps to reproduce

Conditions in the `component.yaml` file are not working correctly. It appears that the argo-workflow component takes the "IF" condition argument literally. `This is something that worked in kubeflow v1.8.0 and KFP 1.8.X (argoworkflow manifest)`

here we  I wrote dummy pipeline that prints /etc/hosts file. If `line_number=true` it should add `-n` argument to `cat` executable to print file with line numbers.

1. Compile following using KFP v2.8.0
```yaml
---
name: kfp-busybox
description: check-conditions

inputs:
- name: file
  type: String
  default: "/etc/hosts"
- name: line_number
  type: Boolean
  optional: true

implementation:
  container:
    args:
      - inputValue: file
      - if:
          cond:
            isPresent: line_number
          then:
          - -n
    image: busybox:latest
    command: [
      "/bin/cat"
    ]
```

3. compiled component:

```yaml
components:
  comp-kfp-busybox:
    executorLabel: exec-kfp-busybox
    inputDefinitions:
      parameters:
        file:
          defaultValue: /etc/hosts
          isOptional: true
          parameterType: STRING
        line_number:
          isOptional: true
          parameterType: BOOLEAN
deploymentSpec:
  executors:
    exec-kfp-busybox:
      container:
        args:
        - '{{$.inputs.parameters[''file'']}}'
        - '{"IfPresent": {"InputName": "line_number", "Then": ["-n"]}}'
        command:
        - /bin/cat
        image: busybox:latest
pipelineInfo:
  name: pipeline
root:
  dag:
    tasks:
      kfp-busybox:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-kfp-busybox
        inputs:
          parameters:
            file:
              componentInputParameter: file
            line_number:
              componentInputParameter: line_number
        taskInfo:
          name: cat-hosts
  inputDefinitions:
    parameters:
      file:
        parameterType: STRING
      line_number:
        parameterType: BOOLEAN
schemaVersion: 2.1.0
sdkVersion: kfp-2.8.0
---
platforms:
  kubernetes:
    deploymentSpec:
      executors:
        exec-kfp-busybox:
          imagePullSecret:
          - secretName: sdk-docker
```
4. upload pipeline to kubeflow platform
5. run pipeline

Output:

```
time="2024-07-16T11:16:04.035Z" level=info msg="capturing logs" argo=true
time="2024-07-16T11:16:04.153Z" level=info msg="capturing logs" argo=true
I0716 11:16:04.212214      25 launcher_v2.go:90] input ComponentSpec:{
  "inputDefinitions": {
    "parameters": {
      "file": {
        "parameterType": "STRING",
        "defaultValue": "/etc/hosts",
        "isOptional": true
      },
      "line_number": {
        "parameterType": "BOOLEAN",
        "isOptional": true
      }
    }
  },
  "executorLabel": "exec-kfp-busybox"
}
I0716 11:16:04.213720      25 cache.go:139] Cannot detect ml-pipeline in the same namespace, default to ml-pipeline.kubeflow:8887 as KFP endpoint.
I0716 11:16:04.213766      25 cache.go:116] Connecting to cache endpoint ml-pipeline.kubeflow:8887
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
cat: can't open '{"IfPresent": {"InputName": "line_number", "Then": ["-n"]}}': No such file or directory
I0716 11:16:04.443096      25 launcher_v2.go:151] publish success.
F0716 11:16:04.443142      25 main.go:49] failed to execute component: exit status 1
time="2024-07-16T11:16:05.156Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1
time="2024-07-16T11:16:06.037Z" level=info msg="sub-process exited" argo=true error="<nil>"
Error: exit status 1

```

as you can see here:

`cat: can't open '{"IfPresent": {"InputName": "line_number", "Then": ["-n"]}}': No such file or directory`

### Expected result

Print file with line numbers for instance:

```text
     1	127.0.0.1	localhost
     2	::1	localhost ip6-localhost ip6-loopback
     3	fe00::0	ip6-localnet
     4	ff00::0	ip6-mcastprefix
     5	ff02::1	ip6-allnodes
     6	ff02::2	ip6-allrouters
```

### Materials and Reference

- https://www.kubeflow.org/docs/components/pipelines/reference/component-spec/
- test example that should cover this usecase: https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/server/test/xgboost_sample_pipeline.yaml#L304
---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by khushiiagrawal**
**Description of your changes:**

Fixed IfPresent condition resolution in component.yaml. The driver now resolves IfPresent conditions in container arguments before passing them to the launcher, preventing JSON strings from being passed as literal command arguments.
 
Fixes #11009 

**Changes:**
- Modified `initPodSpecPatch()` in `driver.go` to call `resolveContainerArgs()` for processing container arguments
- Added `resolveContainerArgs()`, `isConditionClause()`, and `resolveCondition()` functions in `util.go` to handle IfPresent condition resolution
- Added tests in `util_test.go` covering IfPresent conditions with present/absent parameters, else clauses, and multiple values

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: backend/src/v2/driver/util.go [hunk 1]
```diff
@@ -106,3 +108,77 @@ func getItems(value *structpb.Value) (items []*structpb.Value, err error) {
...
+		resolved = []string{resolvedArg}
+	case []interface{}:
+		for _, item := range v {
+			if str, ok := item.(string); ok {
+				resolvedArg, err := resolvePodSpecInputRuntimeParameter(str, executorInput)
+				if err != nil {
+					return nil, err
+				}
+				resolved = append(resolved, resolvedArg)
+			}
```
[the remark this answers is not in the document]
Comment (khushiiagrawal) [reply backend/src/v2/driver/util.go]: implemented

**Comment by khushiiagrawal** [comment]
PTAL @hbelmiro 
thanks!

File: backend/src/v2/driver/util_test.go [hunk 2]
```diff
@@ -158,3 +158,118 @@ func Test_resolvePodSpecRuntimeParameter(t *testing.T) {
...
+			actual, err := resolveContainerArgs(test.args, test.executorInput)
+			if test.wantErr {
+				assert.Error(t, err)
+			} else {
+				assert.NoError(t, err)
+				assert.Equal(t, test.expected, actual)
+			}
+		})
+	}
+}
```
[the remark this answers is not in the document]
Comment (khushiiagrawal) [reply backend/src/v2/driver/util_test.go:622]: resolved

**Comment by khushiiagrawal** [comment]
@droctothorpe  please take a look. 
thanks!

**Comment by khushiiagrawal** [comment]
@hbelmiro  hii,  I'm stuck on the E2E tests,  all 20 of them are timing out. Unit tests work fine though.
Not sure what's causing this or how to debug it. Any suggestions on what I should look at?
Thank you.

**Comment by hbelmiro** [comment]
@khushiiagrawal can you please rebase. We're now [adding the Argo Workflows logs to the HTML report](https://github.com/kubeflow/pipelines/pull/12540) when tests fail. That will be helpful to figure out why the tests are timing out.

**Comment by khushiiagrawal** [comment]
> @khushiiagrawal can you please rebase. We're now [adding the Argo Workflows logs to the HTML report](https://github.com/kubeflow/pipelines/pull/12540) when tests fail. That will be helpful to figure out why the tests are timing out.

Sure.
Thanks!

**Comment by khushiiagrawal** [comment]
@hbelmiro  Please take a look. 
Thanks!

**Comment by hbelmiro** [comment]
@khushiiagrawal can you please rebase so the `/ok-to-test` command can work?

**Comment by khushiiagrawal** [comment]
> @khushiiagrawal can you please rebase so the `/ok-to-test` command can work?

@hbelmiro  Done!

**Comment by khushiiagrawal** [comment]
@hbelmiro  please take a look. now i guess all the cis should pass.
thank you!

**Comment by khushiiagrawal** [comment]
@hbelmiro  Sharing a quick update on the fix (conditions in `component.yaml` not working correctly).

I verified the fix:

 Before (Failing) -

The driver was treating the `IfPresent` condition as a literal file path instead of evaluating the JSON condition.

```text
cat: can't open '{"IfPresent": {"InputName": "line_number", "Then": ["-n"]}}': No such file or directory
F0716 11:16:04.443142      25 main.go:49] failed to execute component: exit status 1
```

After (Working) -

The condition is now correctly detected. Since `line_number` is present, it resolves to `-n` and the command executes successfully.

```text
# Executed: /bin/cat -n /etc/hosts
     1	127.0.0.1	localhost
     2	::1	localhost ip6-localhost ip6-loopback
     3	fe00::0	ip6-localnet
```

On large diff (~1500 lines) -

The actual code change is small (~300 lines). The rest is auto-generated test data.
New driver arguments (e.g. `--pipeline_job_create_time_utc`) required regenerating the golden compiled workflow YAMLs in `test_data/`, which accounts for the large diff.

**Comment by khushiiagrawal** [comment]
@hbelmiro  I tried a lot of things but these checks are still getting failed. The current code implementation resolves the issue completely. 
would really appreciate your guidance here.
thanks!

**Comment by hbelmiro** [comment]
@khushiiagrawal you can see the errors in the HTML reports.

https://github.com/kubeflow/pipelines/actions/runs/21449425915?pr=12598

**Comment by khushiiagrawal** [comment]
@hbelmiro  finally all the checks have been passed, resolved the issue and fixed the needed charges. 
please take a look. 
thank you so much!

**Comment by khushiiagrawal** [comment]
@zazulam  @hbelmiro  i have addressed all the copilot reviews. please take a look.
thanks!

**Comment by khushiiagrawal** [comment]
@hbelmiro  @zazulam  would really appreciate your review. 
thanks!

File: backend/src/v2/driver/util.go [hunk 3]
```diff
@@ -106,3 +105,150 @@ func getItems(value *structpb.Value) (items []*structpb.Value, err error) {
...
+		return fmt.Sprintf("%g", n)
+	case *structpb.Value_BoolValue:
+		if v.GetBoolValue() {
+			return "true"
+		}
+		return "false"
+	case *structpb.Value_NullValue:
+		return ""
+	default:
+		return fmt.Sprintf("%v", v.AsInterface())
```
Comment (hbelmiro) [inline backend/src/v2/driver/util.go]: `pbValueToString()` currently falls back to `%v` formatting (for example `[a b]` / `map[k:v]`), while launcher placeholder substitution uses JSON-style values. Since `resolveContainerArgs()` now resolves placeholders earlier, this can change the final argument format depending on where substitution happens. Could we switch LIST/STRUCT conversion here to JSON for parity?

File: backend/src/v2/driver/util.go [hunk 4]
```diff
@@ -106,3 +105,150 @@ func getItems(value *structpb.Value) (items []*structpb.Value, err error) {
...
+			}
+			resolved = append(resolved, resolvedArg)
+		}
+	default:
+		return nil, fmt.Errorf("unexpected type in IfPresent Then/Else: %T", v)
+	}
+	return resolved, nil
+}
+
+func resolveContainerArgs(args []string, executorInput *pipelinespec.ExecutorInput) ([]string, error) {
```
Comment (hbelmiro) [inline backend/src/v2/driver/util.go:249]: One non-blocking note: we now have additional duplication in placeholder/type resolution logic across driver/launcher paths (this overlap already existed, and this PR expands it). Let's address resolver reuse/consolidation in a [follow-up issue/PR](https://github.com/kubeflow/pipelines/issues/12949) so future placeholder fixes and tests can live in one shared path.

File: backend/src/v2/driver/util.go [hunk 5]
```diff
@@ -26,16 +28,14 @@ import (
 // example input channel looks like "{{$.inputs.parameters['pipelinechannel--val']}}"
 const inputPipelineChannelPattern = `\$.inputs.parameters\['(.+?)'\]`
 
+// fullInputParameterRe matches the complete {{$.inputs.parameters['name']}} placeholder
+// including the surrounding braces, for template substitution in container arguments.
+var fullInputParameterRe = regexp.MustCompile(`\{\{\$\.inputs\.parameters\['(.+?)'\]\}\}`)
```
Comment (hbelmiro) [inline backend/src/v2/driver/util.go]: Nit: the closing brace escapes in this regex are redundant.


```suggestion
var fullInputParameterRe = regexp.MustCompile(`\{\{\$\.inputs\.parameters\['(.+?)']}}`)
```

File: backend/src/v2/driver/util.go [hunk 6]
```diff
@@ -106,3 +105,150 @@ func getItems(value *structpb.Value) (items []*structpb.Value, err error) {
...
+			resolveErr = fmt.Errorf("failed to extract parameter name from: %s", match)
+			return match
+		}
+		paramName := submatch[1]
+		val, ok := executorInput.GetInputs().GetParameterValues()[paramName]
+		if !ok {
+			resolveErr = fmt.Errorf("parameter %q not found in executor input", paramName)
+			return match
+		}
+		return pbValueToString(val)
```
Comment (hbelmiro) [inline backend/src/v2/driver/util.go]: Let's extract this to a dedicated helper.

File: backend/src/v2/driver/util.go [hunk 7]
```diff
@@ -106,3 +105,150 @@ func getItems(value *structpb.Value) (items []*structpb.Value, err error) {
...
+}
+
+func resolveCondition(arg string, executorInput *pipelinespec.ExecutorInput) ([]string, error) {
+	var ifPresent struct {
+		IfPresent struct {
+			InputName string      `json:"InputName"`
+			Then      interface{} `json:"Then"`
+			Else      interface{} `json:"Else"`
+		} `json:"IfPresent"`
+	}
```
Comment (hbelmiro) [inline backend/src/v2/driver/util.go]: This inline anonymous JSON struct makes `resolveCondition` harder to read and evolve. Could we move it to a named type (and optionally use `json.RawMessage` for `Then`/`Else`) so the envelope parsing is explicit and easier to test? The current `interface{}` + anonymous nesting works, but a named schema would improve maintainability.

File: backend/src/v2/driver/util.go [hunk 8]
```diff
@@ -106,3 +105,150 @@ func getItems(value *structpb.Value) (items []*structpb.Value, err error) {
...
+	for _, arg := range args {
+		// Skip args containing output placeholders - these need to be resolved by Argo at runtime
+		// Example: {{$.outputs.parameters['sum'].output_file}}
+		if strings.Contains(arg, "$.outputs") {
+			resolvedArgs = append(resolvedArgs, arg)
+			continue
+		}
+
+		switch {
+		case isConditionClause(arg):
```
Comment (hbelmiro) [inline backend/src/v2/driver/util.go]: Why not `if isConditionClause(arg) {`?

File: backend/src/v2/driver/util_test.go [hunk 9]
```diff
@@ -158,3 +158,314 @@ func Test_resolvePodSpecRuntimeParameter(t *testing.T) {
...
+		},
+	}
+
+	for _, test := range tests {
+		t.Run(test.name, func(t *testing.T) {
+			actual, err := resolveContainerArgs(test.args, test.executorInput)
+			if test.wantErr {
+				assert.Error(t, err)
+			} else {
+				assert.NoError(t, err)
```
Comment (hbelmiro) [inline backend/src/v2/driver/util_test.go]:
```suggestion
				require.NoError(t, err)
```

File: backend/src/v2/driver/util.go (hunk 8 above)
Comment (khushiiagrawal) [reply backend/src/v2/driver/util.go]: agreed, changed to a plain if/else,  much clearer.

File: backend/src/v2/driver/util.go (hunk 5 above)
Comment (khushiiagrawal) [reply backend/src/v2/driver/util.go]: fixed, thanks. the closing }} and ] don't need escaping in a raw regex, removed the redundant backslashes.

File: backend/src/v2/driver/util.go (hunk 3 above)
Comment (khushiiagrawal) [reply backend/src/v2/driver/util.go]: right, ive switched the default case to use json.Marshal, so LIST and STRUCT values are now serialized as JSON (e.g. ["a","b"] / {"k":"v"}) instead of Go's %v format. added a graceful fallback to %v only if marshaling itself fails. this keeps the output consistent with what the launcher produces.

File: backend/src/v2/driver/util.go (hunk 4 above)
Comment (khushiiagrawal) [reply backend/src/v2/driver/util.go:249]: agree. i'll open a PR soon for it. thanks for pointing it.

File: backend/src/v2/driver/util.go (hunk 6 above)
Comment (khushiiagrawal) [reply backend/src/v2/driver/util.go]: sure

**Comment by khushiiagrawal** [comment]
@hbelmiro  i have addressed all the comments , could you please take a look once, i guess we are good to go now.
thanks!
