### PR TITLE
[Backend] Fix user identity extraction logic in getUserIdentity()

### LINKED ISSUE #3752: [Multi User] Make user identity header configurable
/cc @yanniszark @jlewi 
as discussed in https://github.com/kubeflow/pipelines/issues/3645#issuecomment-625872980

Part of https://github.com/kubeflow/pipelines/issues/1223

* [x] UI Server #3753 
* [x] Api Server https://github.com/kubeflow/pipelines/pull/3772 and https://github.com/kubeflow/pipelines/pull/3842

### PR DESCRIPTION
**Pull request by elikatsis**
Signed-off-by: Ilias Katsakioris <elikatsis@arrikto.com>

---

Fixes #3752

The backend incorrectly parses the contents of the `KUBEFLOW_USERID_HEADER`.
Moreover, it totally ignores `KUBEFLOW_USERID_PREFIX`.

Currently, the backend gets the header, splits it on `:` and gets the 2nd element of the result.

The author of this part of code must have been carried away by google headers which look like this:
```
x-goog-authenticated-user-email: accounts.google.com:user
```

However, this is leads to errors for different values of the environment variables. For example:
```
KUBEFLOW_USERID_HEADER = "kubeflow-userid"
KUBEFLOW_USERID_PREFIX = "prefix"
```
In this case, the header should look like this:
```
kubeflow-userid: prefixuser
```
but the apiserver will raise errors.

This PR fixes this issue.

### CODE REVIEW

**Comment by Bobgy** [comment]
@elikatsis Thanks for the fix! Would you mind adding a unit test similar to https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/server/util_test.go#L340?

/assign @chensun @jingzhang36 
/lgtm

**Comment by Bobgy** [comment]
Part of #1223

**Comment by elikatsis** [comment]
Thanks @Bobgy,

I changed the function I added to get the prefix as an argument so that I can add a few more tests easily.

**Comment by chensun** [comment]
Thanks for the fix! +1 on adding tests.
I was relying on the unit tests for my last change, and apparently we didn't have enough coverage.

/lgtm

File: backend/src/apiserver/server/util_test.go [hunk 1]
```diff
@@ -345,6 +345,32 @@ func TestGetUserIdentity(t *testing.T) {
 	assert.Equal(t, "user@google.com", userIdentity)
 }
 
+func TestGetUserIdentityError(t *testing.T) {
+	md := metadata.New(map[string]string{"no-identity-header": "user"})
+	ctx := metadata.NewIncomingContext(context.Background(), md)
+	_, err := getUserIdentity(ctx)
+	assert.NotNil(t, err)
```
Comment (Bobgy) [inline backend/src/apiserver/server/util_test.go:352]: nit: can we also assert the error message here to make sure the error came from missing header

Comment (elikatsis) [reply backend/src/apiserver/server/util_test.go:352]: Done! Thanks

**Comment by Bobgy** [comment]
Thanks for the contribution!
/lgtm

/hold
FYI, travis unit tests are flaky recently. I retried it once for you, but it may not pass. Can you do a commit and push to retry it if it fails again?
/cc @Ark-kun 

Once travis test passed we can unhold.

**Comment by elikatsis** [comment]
Looks like travis succeeded so I'll remove the `hold`.
Also ping @jingzhang36 

/unhold

File: backend/src/apiserver/server/util.go [hunk 2]
```diff
@@ -287,12 +299,7 @@ func getUserIdentity(ctx context.Context) (string, error) {
 			return "", util.NewBadRequestError(errors.New("Request header error: unexpected number of user identity header. Expect 1 got "+strconv.Itoa(len(userIdentityHeader))),
 				"Request header error: unexpected number of user identity header. Expect 1 got "+strconv.Itoa(len(userIdentityHeader)))
 		}
-		userIdentityHeaderFields := strings.Split(userIdentityHeader[0], ":")
-		if len(userIdentityHeaderFields) != 2 {
-			return "", util.NewBadRequestError(errors.New("Request header error: user identity value is incorrectly formatted"),
-				"Request header error: user identity value is incorrectly formatted")
-		}
-		return userIdentityHeaderFields[1], nil
+		return getUserIdentityFromHeader(userIdentityHeader[0], common.GetKubeflowUserIDPrefix())
```
Comment (jingzhang36) [inline backend/src/apiserver/server/util.go:302]: Does GetKubeflowUserIDPrefix() return a prefix with ":" as the last character? Seems that the new logic doesn't require a ":" as the delimiter as the old logic does.

Comment (Bobgy) [reply backend/src/apiserver/server/util.go:302]: Yes, you are right. We no longer require a ":" delimiter. This is expected behavior.
