### PR TITLE
fix(backend): add retry run in v2 api. Fixes #8735

### LINKED ISSUE #8735: fix(backend): KFP v2 API - missing retry run API

### PR DESCRIPTION
**Pull request by Linchin**
**Description of your changes:**
* Added retry run in v2 api proto
* Added support for retry run in v2 api in the backend
* Unit test

Fixes https://github.com/kubeflow/pipelines/issues/8735

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: backend/src/apiserver/server/run_server.go [hunk 1]
```diff
@@ -499,7 +499,17 @@ func (s *RunServer) terminateRun(ctx context.Context, runId string, experimentId
...
+// Applies common logic on v1beta1 and v2beta1 API.
+func (s *RunServer) retryRun(ctx context.Context, runId string, experimentId string) error {
+	err := s.canAccessRun(ctx, runId, &authorizationv1.ResourceAttributes{Verb: common.RbacResourceVerbRetry})
+	if err != nil {
+		return util.Wrap(err, "Failed to authorize the request")
+	}
+	return s.resourceManager.RetryRun(ctx, runId)
+}
+
+// Retarts a run.
```
Comment (chensun) [inline backend/src/apiserver/server/run_server.go:512]: s/Retarts/Terminates/

File: backend/src/apiserver/server/run_server.go [hunk 2]
```diff
@@ -499,7 +499,17 @@ func (s *RunServer) terminateRun(ctx context.Context, runId string, experimentId
 	return s.resourceManager.TerminateRun(ctx, runId)
 }
 
-// Terminates a run.
+// Restarts a run. Not exported.
```
Comment (chensun) [inline backend/src/apiserver/server/run_server.go:502]: Maybe use "retry" to be more aligned with the method name?

"Not exported." is not needed and obvious since the function starts with the lowercase letter.

File: backend/src/apiserver/server/run_server.go [hunk 3]
```diff
@@ -661,6 +668,21 @@ func (s *RunServer) TerminateRun(ctx context.Context, request *apiv2beta1.Termin
 	return &empty.Empty{}, nil
 }
 
+// Restarts a run.
```
Comment (chensun) [inline backend/src/apiserver/server/run_server.go:671]: s/Restarts/Retries

File: backend/api/v2beta1/run.proto [hunk 4]
```diff
@@ -436,4 +443,13 @@ message ReadArtifactRequest {
 message ReadArtifactResponse {
   // Byte array of the artifact content.
   bytes data = 1;
+}
+
+message RetryRunRequest {
+ // The ID of the parent experiment.
+ string experiment_id = 1;
+
+
```
Comment (gkcalat) [inline backend/api/v2beta1/run.proto:452]: NIT: remove empty line

File: backend/api/v2beta1/run.proto [hunk 5]
```diff
@@ -436,4 +443,13 @@ message ReadArtifactRequest {
...
+ // The ID of the run to be Retried.
```
Comment (gkcalat) [inline backend/api/v2beta1/run.proto:453]: NIT: `Retried` -> `retried`

File: backend/src/apiserver/server/run_server.go (hunk 2 above)
Comment (Linchin) [reply backend/src/apiserver/server/run_server.go]: Thank you so much! I fixed this and other comments in this file.

File: backend/src/apiserver/server/run_server.go (hunk 3 above)
Comment (Linchin) [reply backend/src/apiserver/server/run_server.go]: Thank you, fixed.

File: backend/src/apiserver/server/run_server.go (hunk 1 above)
Comment (Linchin) [reply backend/src/apiserver/server/run_server.go]: Thank you, fixed.

File: backend/src/apiserver/server/run_server.go [hunk 6]
```diff
@@ -499,7 +499,17 @@ func (s *RunServer) terminateRun(ctx context.Context, runId string, experimentId
 	return s.resourceManager.TerminateRun(ctx, runId)
 }
 
-// Terminates a run.
+// Restarts a run. Not exported.
+// Applies common logic on v1beta1 and v2beta1 API.
+func (s *RunServer) retryRun(ctx context.Context, runId string, experimentId string) error {
```
Comment (gkcalat) [inline backend/src/apiserver/server/run_server.go:504]: `experimentId` not being used here. For v2, we can verify the provided `experimentId` with the one retrieved from `GetRun`. If they don't match or if `GetRun` returns an error, fail quickly. For v1, we simply read the `experimentId` from the same `GetRun` result as `experimentId` will be empty.

The `experimentId` can then be passed to the resource manager and instead of `getNamespaceFromRunId` we can call `GetNamespaceFromExperimentId` to save one extra call there.

The same logic is [already applied](https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/server/run_server.go#L492-L498) to `TerminateRun`.

WDYT? 

/CC @chensun

File: backend/src/apiserver/server/run_server_test.go [hunk 7]
```diff
@@ -1502,3 +1502,42 @@ func TestReadArtifacts_Succeed(t *testing.T) {
...
+		"param2": &structpb.Value{Kind: &structpb.Value_BoolValue{BoolValue: true}},
+		"param3": &structpb.Value{Kind: &structpb.Value_ListValue{ListValue: v2RuntimeListParams}},
+		"param4": &structpb.Value{Kind: &structpb.Value_NumberValue{NumberValue: 12}},
+		"param5": &structpb.Value{Kind: &structpb.Value_StructValue{StructValue: v2RuntimeStructParams}},
+	}
+
+	pipelineSpecStruct := &structpb.Struct{}
+	yaml.Unmarshal([]byte(v2SpecHelloWorld), pipelineSpecStruct)
+
+	run := &apiv2beta1.Run{
```
Comment (gkcalat) [inline backend/src/apiserver/server/run_server_test.go:1528]: NIT: add a comment explaining why this run will achieve the `FAILED` state.

File: backend/src/apiserver/server/run_server_test.go [hunk 8]
```diff
@@ -1502,3 +1502,42 @@ func TestReadArtifacts_Succeed(t *testing.T) {
...
+			PipelineSpec: pipelineSpecStruct,
+		},
+		RuntimeConfig: &apiv2beta1.RuntimeConfig{
+			Parameters:   v2RuntimeParams,
+			PipelineRoot: "model-pipeline-root",
+		},
+	}
+	run, err := server.CreateRun(nil, &apiv2beta1.CreateRunRequest{Run: run})
+	assert.Nil(t, err)
+
```
Comment (gkcalat) [inline backend/src/apiserver/server/run_server_test.go:1541]: NIT: verify that the state is `FAILED`

File: backend/src/apiserver/server/run_server_test.go [hunk 9]
```diff
@@ -1502,3 +1502,42 @@ func TestReadArtifacts_Succeed(t *testing.T) {
...
+	_, err = server.RetryRun(nil, &apiv2beta1.RetryRunRequest{RunId: run.RunId})
```
Comment (gkcalat) [inline backend/src/apiserver/server/run_server_test.go:1542]: NIT: add a case with retried a terminated run

File: backend/src/apiserver/resource/resource_manager.go [hunk 10]
```diff
@@ -719,15 +719,15 @@ func (r *ResourceManager) RetryRun(ctx context.Context, runId string) error {
 		return util.Wrapf(err, "Failed to retry run %s", runId)
 	}
 
+	if namespace == "" {
```
Comment (gkcalat) [inline backend/src/apiserver/resource/resource_manager.go:722]: Good catch! Thank you!

**Review by gkcalat — COMMENTED** [review]
Thank you @Linchin. I left a few comments. Please, correct me where I was wrong.

File: backend/api/v2beta1/run.proto (hunk 4 above)
Comment (Linchin) [reply backend/api/v2beta1/run.proto:452]: Thank you, removed.

File: backend/src/apiserver/server/run_server.go (hunk 6 above)
Comment (chensun) [reply backend/src/apiserver/server/run_server.go:504]: Good catch, we shouldn't even pass experimentId here.
Retry is just to retry as-is, to allow changing experiment and more, users can use clone.
https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v1beta1/run.proto#L180-L183

File: backend/api/v2beta1/run.proto [hunk 11]
```diff
@@ -436,4 +443,13 @@ message ReadArtifactRequest {
 message ReadArtifactResponse {
   // Byte array of the artifact content.
   bytes data = 1;
+}
+
+message RetryRunRequest {
+ // The ID of the parent experiment.
+ string experiment_id = 1;
```
Comment (chensun) [inline backend/api/v2beta1/run.proto:450]: Remove `experiment_id`
Not presented in v1 either:

https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v1beta1/run.proto#L180-L183

**Review by chensun — CHANGES_REQUESTED** [review]

File: backend/api/v2beta1/run.proto (hunk 5 above)
Comment (Linchin) [reply backend/api/v2beta1/run.proto:453]: Thank you for catching this! Fixed.

File: backend/api/v2beta1/run.proto (hunk 11 above)
Comment (Linchin) [reply backend/api/v2beta1/run.proto:450]: The `experiment_id` is added to be consistent with other v2 methods in this proto, including [GetRunRequest](https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v2beta1/run.proto#L345), [TerminateRunRequest](https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v2beta1/run.proto#L379), [ArchiveRunRequest](https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v2beta1/run.proto#L398), [UnarchiveRunRequest](https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v2beta1/run.proto#L406), and [DeleteRunRequest](https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v2beta1/run.proto#L414). All these messages include an `experiment_id` field because there is an `experiment_id` section in the API path ([example](https://github.com/kubeflow/pipelines/blob/b3de27a7d01ee7febef58b92abc52ffb1f49b4a7/backend/api/v2beta1/run.proto#L73)). I agree that here `experiment_id` is redundant, although it follows [AIP design principle](https://google.aip.dev/122). However, I do think we need to maintain consistency among all methods across the same service, i.e., either all methods within RunService should have `experiment_id` as part of the path, or no method does.

Comment (chensun) [reply backend/api/v2beta1/run.proto:450]: Synced offline, given that experiment is a parent resource of run, we need to keep the experiment_id here. But the current implementation of ignoring experiment id should be fixed as well. This is not a blocker for the PR, consider the same pattern exists in GetRuns, GetJobs, etc.--although we do have validation that could complain "the run_id doesn't belong to the experiment" for those APIs, while such validation is missing for the retry run. 
We can fix the validation across all the APIs to check if "run id can be find in the given experiment id" post beta0 release.

**Review by chensun — APPROVED** [review]
/lgtm
/approve

Thanks!

File: backend/src/apiserver/server/run_server.go (hunk 6 above)
Comment (Linchin) [reply backend/src/apiserver/server/run_server.go:504]: Added logic to verify the experiment id is correct.

File: backend/api/v2beta1/run.proto (hunk 11 above)
Comment (Linchin) [reply backend/api/v2beta1/run.proto:450]: Before seeing your comment, I added logic to verify the experiment id is correct.

**Comment by gkcalat** [comment]
Thank you, @Linchin!

/lgtm
/approve
