### PR TITLE
fix(backend): Decompress workflow node statuses if necessary. Fixes #6547

### LINKED ISSUE #6547: [backend] Retries fail silently for runs with compressed or offloaded node statuses
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? standalone

*  KFP version: 1.5.1

*  KFP SDK version: n/a

### Steps to reproduce

- Start a run with at least one failed task that includes enough nodes that the workflow object populates `status.compressedNodes` rather than `status.nodes`.
- Retry the run
- Failed nodes aren't retried, but no error is raised

### Expected result

Failed nodes are retried.

### Materials and Reference

Argo compresses node statuses when they're too big, and if compression isn't enough, they're optionally offloaded to the database: https://argoproj.github.io/argo-workflows/offloading-large-workflows/. The kfp retry logic doesn't appear to check compressed or offloaded nodes, so when there are too many node statuses, retries don't appear to have any effect.

We should be able to use `DecompressWorkflow` to handle compressed node statuses: https://github.com/argoproj/argo-workflows/blob/2e174bd4c585ccf72e34c8f72703a0950a67460c/workflow/packer/packer.go#L29. But to handle offloaded status, I think we'd either need to talk to the argo database directly, or use the argo api. I don't see argo persistence or offloaded statuses enabled in the helm or kustomize manifests in this repo, so maybe it's good enough to handle compressed node statues and error on offloaded statuses for now.

Thoughts @Bobgy?

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by jmcarp**
Fixes https://github.com/kubeflow/pipelines/issues/6547

**Description of your changes:**

- Decompress workflow node statuses if compressed.
- Error on offloaded node statuses. If we want to support this case, I think we'd need to either connect the kfp server to the argo database or fetch the statuses using the argo server. 

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Bobgy** [comment]
/assign @capri-xiyue
Can you help review? This looks like a useful fix

File: backend/src/apiserver/resource/resource_manager.go [hunk 1]
```diff
@@ -585,6 +586,14 @@ func (r *ResourceManager) RetryRun(ctx context.Context, runId string) error {
 		return util.NewInternalServerError(err, "Failed to retrieve the runtime pipeline spec from the run")
 	}
 
+	if err := packer.DecompressWorkflow(workflow.Workflow); err != nil {
+		return util.NewInternalServerError(err, "Failed to decompress workflow")
+	}
+
+	if workflow.Status.OffloadNodeStatusVersion != "" {
```
Comment (capri-xiyue) [inline backend/src/apiserver/resource/resource_manager.go:593]: Can we add UT to verify the case when the workflow has offload node status?

**Comment by capri-xiyue** [comment]
@Bobgy  Can you help approve this PR?
