### PR TITLE
Fix unresolved create/schedule time placeholders

### LINKED ISSUE #12616: [backend] Problem with create and schedule time placeholders for pipeline inputs
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)?
Kubeflow manifests 0.11.0 with MySQL as the storage backend for pipeline definitions ([using the `applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user` manifests](https://github.com/kubeflow/manifests/tree/master/applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user))
*  KFP version: 
2.15.0
*  KFP SDK version: 
2.15.2

### Steps to reproduce

Pipeline definition
``` python
from kfp import dsl
from kfp.dsl import component
from kfp.compiler import Compiler


@component(base_image="python:3.12",)
def print_op(msg: str, value: str):
    print(msg, value)


@dsl.pipeline(name="pipeline-with-placeholders")
def my_pipeline():
    print_op(
        msg="job name:",
        value=dsl.PIPELINE_JOB_NAME_PLACEHOLDER,
    )
    print_op(
        msg="job resource name:",
        value=dsl.PIPELINE_JOB_RESOURCE_NAME_PLACEHOLDER,
    )
    print_op(
        msg="job id:",
        value=dsl.PIPELINE_JOB_ID_PLACEHOLDER,
    )
    print_op(
        msg="task name:",
        value=dsl.PIPELINE_TASK_NAME_PLACEHOLDER,
    )
    print_op(
        msg="task id:",
        value=dsl.PIPELINE_TASK_ID_PLACEHOLDER,
    )
    print_op(
        msg="create time:",
        value=dsl.PIPELINE_JOB_CREATE_TIME_UTC_PLACEHOLDER,
    )
    print_op(
        msg="schedule time:",
        value=dsl.PIPELINE_JOB_SCHEDULE_TIME_UTC_PLACEHOLDER,
    )


if __name__ == "__main__":
    pipeline_filename = "pipeline-with-placeholders.yaml"
    Compiler().compile(
        pipeline_func=my_pipeline,
        package_path=pipeline_filename,
        kubernetes_manifest_format=False,
    )
```

Compiled by running the script and then uploaded manually via the UI as a shared pipeline.
Running this pipeline shows that placeholders for the two last ops are not properly resolved, the rest of inputs are properly resolved:

Image
Image

### Expected result
The two placeholders should be properly resolved by KFP to some sensible values. 

### Materials and Reference
To me this seems like an issue in the `resolveInputParameter` function, https://github.com/kubeflow/pipelines/blob/master/backend/src/v2/driver/resolve.go#L430, there are missing cases for the two templates `{{$.pipeline_job_schedule_time_utc}}` and `{{$.pipeline_job_create_time_utc}}`. 

The placeholders are defined in the kfp.dsl package https://kubeflow-pipelines.readthedocs.io/en/sdk-2.15.2/source/dsl.html#kfp.dsl.PIPELINE_JOB_CREATE_TIME_UTC_PLACEHOLDER

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by sameerdattav**
Fixes #12616

This PR adds missing placeholder resolution for:
- PIPELINE_JOB_CREATE_TIME_UTC_PLACEHOLDER
- PIPELINE_JOB_SCHEDULE_TIME_UTC_PLACEHOLDER

Previously, these placeholders were not handled in the backend resolver
and remained unresolved at runtime.

Unit tests added to cover both cases. (resolve_test.go)

### CODE REVIEW

**Comment by sameerdattav** [comment]
Note: I noticed that #12627 addresses a related issue using a broader MLMD-based approach.

This PR intentionally keeps the fix minimal and scoped to placeholder resolution, with focused unit tests added in resolve_test.go, in line with the "good first issue" label.

The placeholders now resolve to RFC3339 UTC timestamps at resolution time. 
Happy to adjust the timestamp source if maintainers prefer MLMD-backed values instead.

File: backend/src/v2/driver/resolve.go [hunk 1]
```diff
@@ -427,6 +427,11 @@ func resolveInputParameter(
 				v = structpb.NewStringValue(opts.TaskName)
 			case "{{$.pipeline_task_uuid}}":
 				v = structpb.NewStringValue(fmt.Sprintf("%d", opts.DAGExecutionID))
+				//work
```
Comment (droctothorpe) [inline backend/src/v2/driver/resolve.go]: Nit: please remove this comment.

File: backend/src/v2/driver/driver.go [hunk 2]
```diff
@@ -87,6 +87,10 @@ type Options struct {
 	MLMDServerPort string
 
 	CaCertPath string
+
+	// Added for resolving pipeline job time placeholders
```
Comment (droctothorpe) [inline backend/src/v2/driver/driver.go]: Please delete this comment and add a line break between these two options to match the other options.
