### PR TITLE
tests: Fixed presubmits. Fixes #4412

### LINKED ISSUE #4412: Presubmits fail due to requesting old Kubernetes version
https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubeflow_pipelines/4410/kubeflow-pipeline-e2e-test/1298391823319830528
```
gcloud beta container clusters create e2e-7a629eb-4885 --num-nodes=2 --machine-type=e2-standard-8 --enable-autoscaling --max-nodes=8 --min-nodes=2 --workload-pool=ml-pipeline-test.svc.id.goog --cluster-version=1.14
WARNING: Currently VPC-native is not the default mode during cluster creation. In the future, this will become the default mode and can be disabled using `--no-enable-ip-alias` flag. Use `--[no-]enable-ip-alias` flag to suppress this warning.
WARNING: Newly created clusters and node-pools will have node auto-upgrade enabled by default. This can be disabled using the `--no-enable-autoupgrade` flag.
WARNING: Starting with version 1.18, clusters will have shielded GKE nodes by default.
WARNING: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s). 
This will enable the autorepair feature for nodes. Please see https://cloud.google.com/kubernetes-engine/docs/node-auto-repair for more information on node autorepairs.
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.14" fou
```

### PR DESCRIPTION
**Pull request by Ark-kun**
Fixes https://github.com/kubeflow/pipelines/issues/4412

### CODE REVIEW

File: test/deploy-cluster.sh [hunk 1]
```diff
@@ -80,7 +79,7 @@ else
     # reference: https://cloud.google.com/compute/docs/access/service-accounts#accesscopesiam
     SCOPE_ARG="--scopes=storage-rw,cloud-platform"
   fi
-  gcloud beta container clusters create ${TEST_CLUSTER} ${SCOPE_ARG} ${NODE_POOL_CONFIG_ARG} ${WI_ARG} ${KUBERNETES_VERSION_ARG}
+  gcloud beta container clusters create ${TEST_CLUSTER} ${SCOPE_ARG} ${NODE_POOL_CONFIG_ARG} ${WI_ARG}
```
Comment (Bobgy) [inline test/deploy-cluster.sh:82]: Shall we pin the regular channel instead?

**Review by Bobgy — COMMENTED** [review]
Thank you for the quick fix!
