### PR TITLE
Parametrize the image used for the Tensorboard viewer

### LINKED ISSUE #3232: Tensorboard does not work in a private GKE cluster because image is hard coded
### What steps did you take:

Train a Tensorflow model in a private GKE cluster and use Kubeflow Pipelines to open a Tensorboard instance.

### What happened:

It fails because it tries to pull a public image (e.g. `tensorflow/tensorflow:2.0.0`) and there's no way to override it from manifests due to it being hard coded here: https://github.com/kubeflow/pipelines/blob/0.2.5/frontend/server/k8s-helper.ts#L104.

### What did you expect to happen:

We should have a way to specify which tensorflow image to use (like any other image in kubeflow/manifests). This is the approach used by jupyter-web-app (https://github.com/kubeflow/manifests/blob/master/jupyter/jupyter-web-app/base/config-map.yaml) in which you can specify which notebook images we want to use.

### Environment:

How did you deploy Kubeflow Pipelines (KFP)? Through kfctl_istio_dex.v1.0.0.yaml manifest.

KFP version: 0.2.3

KFP SDK version: 0.2.4.1

/kind bug

### PR DESCRIPTION
**Pull request by rafaelbarreto87**
Right now, the image used by the Tensorboard viewer is hard-coded and it's not possible to override it. This is a problem when running Kubeflow Pipelines in a cluster without access to the internet or public repositories. This solves the issue by parameterizing the image name through an environment variable.

Fixes #3232.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/pipelines/3235)

### CODE REVIEW

**Comment by rmgogogo** [comment]
/cc jingzhang36
Jing can review/approve

File: frontend/server/app.ts [hunk 1]
```diff
@@ -121,7 +121,10 @@ function createUIServer(options: UIConfigs) {
   registerHandler(
     app.post,
     '/apps/tensorboard',
-    getCreateTensorboardHandler(options.viewer.tensorboard.podTemplateSpec),
+    getCreateTensorboardHandler(
```
Comment (Bobgy) [inline frontend/server/app.ts]: app.test.ts has integration tests for each endpoint.
It doesn't currently cover tensorboard endpoint.

Do you want to contribute?

File: frontend/server/app.ts [hunk 2]
```diff
@@ -121,7 +121,10 @@ function createUIServer(options: UIConfigs) {
...
+      options.viewer.tensorboard.tfImageName,
+      options.viewer.tensorboard.podTemplateSpec,
+    ),
```
[the remark this answers is not in the document]
Comment (rafaelbarreto87) [reply frontend/server/app.ts]: Good call.

File: frontend/server/app.ts (hunk 1 above)
Comment (rafaelbarreto87) [reply frontend/server/app.ts]: Not sure I'll have time this week, but I can take a look in the next one.

File: frontend/server/app.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (Bobgy) [reply frontend/server/app.ts]: Hi @rafaelbarreto87, I think this is the last change we'd like to request. The PR is good to be merged after this.

File: frontend/server/k8s-helper.ts [hunk 3]
```diff
@@ -146,10 +147,9 @@ export async function getTensorboardInstance(
           viewer.body.spec.type === 'tensorboard'
         ) {
           const address = `http://${viewer.body.metadata.name}-service.${namespace}.svc.cluster.local:80/tensorboard/${viewer.body.metadata.name}/`;
-          const version = viewer.body.spec.tensorboardSpec.tensorflowImage
-            ? viewer.body.spec.tensorboardSpec.tensorflowImage.replace('tensorflow/tensorflow:', '')
-            : '';
-          return { podAddress: address, tfVersion: version };
+          const tfImageParts = viewer.body.spec.tensorboardSpec.tensorflowImage.split(':', 1);
```
Comment (Bobgy) [inline frontend/server/k8s-helper.ts]: This line has a bug:
```
'tensorflow:2.0.0'.split(':', 1) === ["tensorflow"]
```
So the next line of tfVersion will always be empty, because tfImageParts.length is always 1.

Comment (rafaelbarreto87) [reply frontend/server/k8s-helper.ts]: You're right. This used to not have the `1`. I misunderstood the documentation. Not sure how this ever worked. Sending a patch...

Comment (rafaelbarreto87) [reply frontend/server/k8s-helper.ts]: FYI https://github.com/kubeflow/pipelines/pull/3356
