### PR TITLE
fix(logging): reduce verbose logging for security. Fixes #12293

### LINKED ISSUE #12293: [bug] Reduce verbose error logging to improve security
### Environment
*  How do you deploy Kubeflow Pipelines (KFP)?
   All deployment methods (this affects logging across all installations)

*  KFP version:
   All versions (security issue affects error handling)

### Steps to reproduce
1. Make invalid calls to trigger error conditions:
- /pipeline/k8s/pod
- /pipeline/k8s/pod/events
- /pipeline/artifacts/s3/[bucket]/kfp/[node]/[pod]/[file]
- /pipeline/api/v1beta1/pipelines/upload
2. Observe that verbose error messages allow for scripts to be executed or errors that contain potentially sensitive information

Examples:

#### /pipeline/k8s/pod/events?podname=test-pod-name&podnamespace=test-namespace%7d%7dt93g1%3Cscript%3Ealert(1)%3C%2fscript%3Ej66h

Image

Image

#### /pipeline/k8s/pod?podname=test-pod-name&podnamespace=test-namespace%7d%7dt93g1%3Cscript%3Ealert(1)%3C%2fscript%3Ej66h

Image

Image

(same can be done here when attaching script to pod name instead of namespace name)

pipeline/artifacts/s3/bucketovz9h%3cscript%3ealert(1)%3c%2fscript%3eq0bq2/bucket/kfp/node/pod/main.log?namespace=test-ns

Image

Image

(same can be done here when attaching script to node, pod, and file names instead of bucket name)

#### pipeline/apis/v1beta1/pipelines/upload?name=test&description=

*See error containing information referencing code and files running on the application server*

### Expected result

Example of secure error handling:
- `{"error": "Error when listing pod events for pod in namespace", "code": 400}`
- `{"error": "Failed to get object in bucket", "code": 400}`
- `{"error": "Failed to read pipeline", "code": 400}`

### Materials and reference
N/A

### Proposed Solution
Implement  more generic error responses for invalid requests

### Labels
/area security

### PR DESCRIPTION
**Pull request by JerT33**
**Description of your changes:**
Sanitizes error logging in pipeline upload and K8s pod API endpoints within the frontend service. This help prevents information disclosure by returning generic error responses, while preserving debug information for troubleshooting. This also helps prevent against the ability to run scripts as shown in #12293

Fixes #12293

Testing Evidence:
### bucket

Original:
N/A

Script:
pipeline/artifacts/s3/bucketovz9h%3cscript%3ealert(1)%3c%2fscript%3eq0bq2/bucket/kfp/node/pod/main.log?namespace=test-ns
Screenshot 2025-12-03 at 8 28 16 PM

## pipeline/k8s/pod/events (podnamespace)

Original:
/pipeline/k8s/pod/events?podname=ml-pipeline-ts9vx-system-dag-driver-1158075769&podnamespace=kubeflow
Screenshot 2025-12-03 at 8 24 13 PM

Script:
pipeline/k8s/pod/events?podname=ml-pipeline-ts9vx-system-dag-driver-1158075769&podnamespace=kubeflownfjz0%3cscript%3ealert(1)%3c%2fscript%3ex5j6w
Screenshot 2025-12-03 at 8 24 36 PM

## pipeline/apps/tensorboard (namespace)

Original:
/pipeline/apps/tensorboard?logdir=/&namespace=default
Screenshot 2025-12-03 at 8 20 59 PM

Script:
/pipeline/apps/tensorboard?logdir=/&namespace=defaultwpsqm%253Cscript%25s3Ealert(1)%253C/script%253Ekxsnh
Screenshot 2025-12-03 at 8 22 20 PM

## pipeline/k8s/pod 

Original:
/pipeline/k8s/pod?podname=pipeline-ts9vx-system-dag-driver-1158075769&podnamespace=kubeflow
Screenshot 2025-12-03 at 8 23 05 PM

### podname 

Script:
pipeline/k8s/pod?podname=pipeline-ts9vx-system-dag-driver-1158075769r8e1n%3cscript%3ealert(1)%3c%2fscript%3ez3xor&podnamespace=kubeflow
Screenshot 2025-12-03 at 8 23 32 PM

### podnamespace
/pipeline/k8s/pod?podname=pipeline-ts9vx-system-dag-driver-1158075769&podnamespace=kubeflownfjz0%3cscript%3ealert(1)%3c%2fscript%3ex5j6w
Screenshot 2025-12-03 at 8 28 16 PM

## pipeline/k8s/pod

Original:
pipeline/k8s/pod?podname=ml-pipeline-ts9vx-system-dag-driver-1158075769&podnamespace=kubeflow
Screenshot 2025-12-03 at 9 21 22 PM

Invalid Input:
pipeline/k8s/pod?podname=%5C*&podnamespace=kubeflow
Screenshot 2025-12-03 at 9 22 39 PM

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: backend/src/apiserver/server/pipeline_upload_server.go [hunk 1]
```diff
@@ -98,14 +98,14 @@ func (s *PipelineUploadServer) uploadPipeline(api_version string, w http.Respons
 	glog.Infof("Upload pipeline called")
 	file, header, err := r.FormFile(FormFileKey)
 	if err != nil {
-		s.writeErrorToResponse(w, http.StatusBadRequest, util.Wrap(err, "Failed to read pipeline from file"))
+		s.writeErrorToResponse(w, http.StatusBadRequest, errors.New("Failed to read a pipeline"))
```
Comment (droctothorpe) [inline backend/src/apiserver/server/pipeline_upload_server.go]: I think the wrapped error is helpful. What's the rationale behind scrapping it? Maybe it can log to the backend but not be exposed in the frontend.

Comment (droctothorpe) [reply backend/src/apiserver/server/pipeline_upload_server.go]: The above applies to all of the suppressed error logs.

File: frontend/server/k8s-helper.ts [hunk 2]
```diff
@@ -268,9 +268,8 @@ export async function getPod(
     const { body } = await k8sV1Client.readNamespacedPod(podName, podNamespace);
     return [body, undefined];
   } catch (error) {
-    const { message, additionalInfo } = await parseError(error);
-    const userMessage = `Could not get pod ${podName} in namespace ${podNamespace}: ${message}`;
-    return [undefined, { message: userMessage, additionalInfo }];
+    const userMessage = `Could not get pod in namespace`;
```
Comment (droctothorpe) [inline frontend/server/k8s-helper.ts]: I think it's helpful to log the pod name. Instead of scrapping that altogether, can you sanitize the input?

Comment (droctothorpe) [reply frontend/server/k8s-helper.ts]: Applies to the configmap as well.

File: backend/src/apiserver/server/pipeline_upload_server.go (hunk 1 above)
Comment (JerT33) [reply backend/src/apiserver/server/pipeline_upload_server.go]: No specific rational, just wanted to remove the full error log from the response. Updated to now log the original error, but return a more vague message in the response. Thanks for the call outs here

File: frontend/server/k8s-helper.ts (hunk 2 above)
Comment (JerT33) [reply frontend/server/k8s-helper.ts]: Updated to check these resource values and only log them if they are valid. Also added some test cases from examples shown in #12293

**Comment by droctothorpe** [comment]
Thanks for the incorporating the feedback, @JerT33. 

/lgtm

**Comment by droctothorpe** [comment]
Looks like there are some test errors. Also, can you please squash your commits to just one commit. Thanks!

**Comment by droctothorpe** [comment]
Looks like you have some merge conflicts that need to be addressed in order to rebase, @JerT33.
