### PR TITLE
fix(frontend): show logs for terminated pods. Fixes #11969 

### LINKED ISSUE #11969: [frontend] Kubeflow pipelines v2.4.1 fails to show logs from centraldashboard
### Environment

*  How did you deploy Kubeflow Pipelines (KFP)? ➡ as part of a full Kubeflow installation based on kubeflow/manifests

*  KFP version: 2.4.1

### Steps to reproduce

1. Launch a pipeline run
2. Click on one of the pipeline steps in the rendered graph
3. Click on the "Logs" tab in the sidebar that opens up
4. Observe that there is an error "Failed to retrieve pod logs."
5. Click on "Details" regarding the error and observe "**An error occurred** Error response: Could not get main container logs: Error: Unable to retrieve workflow status: [object Object]."

### Expected result

Logs are shown as expected

### Materials and Reference

There was a previous slack conversation about this: https://cloud-native.slack.com/archives/C073N7BMLB1/p1749200433335229

Browserconsole log:
```
Apis.ts:548 
            
            
            GET https://kubeflow.example.com/pipeline/k8s/pod/logs?podname=mv-pipeline-4fvs9-workflow-name-3377574918&runid=af6ee3e9-bc6d-492c-9c00-43db42abc304&podnamespace=working-group-name 500 (Internal Server Error)
_fetch @ Apis.ts:548
getPodLogs @ Apis.ts:126
_loadSelectedNodeLogs @ RunDetails.tsx:1070
_loadSidePaneTab @ RunDetails.tsx:1045
(anonymous) @ RunDetails.tsx:1009
wi @ react-dom.production.min.js:131
Ei @ react-dom.production.min.js:131
Cl @ react-dom.production.min.js:252
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:120
wl @ react-dom.production.min.js:244
pl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:120
Zo @ react-dom.production.min.js:121
Qo @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
Ar @ react-dom.production.min.js:82
Utils.tsx:37  Response for path: k8s/pod/logs?podname=mv-pipeline-4fvs9-workflow-name-3377574918&runid=af6ee3e9-bc6d-492c-9c00-43db42abc304&podnamespace=working-group-name was not 'ok'

Response was: Could not get main container logs: Error: Unable to retrieve workflow status: [object Object].
error @ Utils.tsx:37
_fetch @ Apis.ts:553
await in _fetch
getPodLogs @ Apis.ts:126
_loadSelectedNodeLogs @ RunDetails.tsx:1070
_loadSidePaneTab @ RunDetails.tsx:1045
(anonymous) @ RunDetails.tsx:1009
wi @ react-dom.production.min.js:131
Ei @ react-dom.production.min.js:131
Cl @ react-dom.production.min.js:252
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:120
wl @ react-dom.production.min.js:244
pl @ react-dom.production.min.js:223
(anonymous) @ react-dom.production.min.js:121
t.unstable_runWithPriority @ scheduler.production.min.js:18
Jo @ react-dom.production.min.js:120
Zo @ react-dom.production.min.js:121
Qo @ react-dom.production.min.js:120
se @ react-dom.production.min.js:285
Ar @ react-dom.production.min.js:82

```

---

Impacted by this bug? Give it a 👍.

### PR DESCRIPTION
**Pull request by AnaySh**
Fixes #11969 

### Description

When pods are garbage collected from the Kubernetes cluster, the Logs tab in the KFP UI displays "Failed to retrieve pod logs" even for V2 runs even though executor logs are stored in object storage as `executor-logs` artifacts.     

 The existing pod logs retrieval in the frontend calls a backend endpoint with a three-tier fallback strategy:                      
  1. Fetches logs directly from the pod via K8s API → fails when pod is garbage collected                                            
  2. Uses the Argo Workflow to find the path to `main.log` in artifact storage → fails when the workflow is garbage collected          
  3. Uses static Argo configuration to query `main.log` → fails when not configured or Argo doesn't save logs to main.log  

For V2 pipelines, the KFP SDK publishes executor logs as MLMD artifacts named `executor-logs` (when using the `--publish_logs` flag). However, the existing log retrieval logic doesn't attempt to use them.  

This PR adds a fourth-tier fallback in the `RuntimeNodeDetailsV2` component that activates when the backend's three-tier strategy fails using helper functions from`frontend/src/mlmd/MlmdUtils.ts`.  

### Pictures

Before this fix, the UI shows an error when looking up logs once pods are garbage collected:

image

After this fix, the `executor-logs` artifact is used for V2 run to display the pod logs in the UI correctly:

fix

**Checklist:**
- [x] You have [signed off your commits](https://www.kubeflow.org/docs/about/contributing/#sign-off-your-commits)
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

File: frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx [hunk 1]
```diff
@@ -325,6 +334,34 @@ async function getLogsInfo(execution: Execution, runId?: string): Promise<Map<st
     logsDetails = await Apis.getPodLogs(runId!, podName, podNameSpace, createdAt);
     logsInfo.set(LOGS_DETAILS, logsDetails);
   } catch (err) {
+    // Primary method failed, try to get logs from executor-logs artifact in MLMD
```
Comment (droctothorpe) [inline frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx:337]: This is fantastic, @AnaySh! My only note is would it make more sense for this logic to be part of `getPodLogs` since it's already handling fallback logic and IMO there's better decomposition that way?

Comment (AnaySh) [reply frontend/src/components/tabs/RuntimeNodeDetailsV2.tsx:337]: Great Point @droctothorpe! I considered that at first, but the current `getPodLogs` handler runs on the server, which doesn't have access to the MLMD client. Adding a new MLMD client to the server would involve adding a gRPC dependency and extending the frontend API and React component to pass the execution ID. 

Happy to discuss if consolidating is preferred, but it would be a larger change spread across multiple files, including creating a new server-side MLMD client that uses grpc-js instead of grpc-web!

**Comment by droctothorpe** [comment]
/approve
/lgtm

Kudos, @AnaySh ! 🎉
