### PR TITLE
fix(backend): reduce confusing ReadArtifact errors for metrics in api server. Fixes #3699

### LINKED ISSUE #3699: API-server is constantly failing with ReadArtifact errors trying to read non-existing metrics artifacts
I constantly see these errors  in the stackdriver logs (even when I do not interact with the cluster).

The component mentioned in the log does not have `mlpipeline-metrics` output.

KFP backend v0.2.4

```
020-05-06 00:41:30.389 PDT
"ResourceNotFoundError: artifact runs/2e5e1591-b8b8-4cd0-938f-3b48742b448d/nodes/tfx-pipeline-7zzn4-832547870/artifacts/mlpipeline-metrics not found."
Error
2020-05-06 00:41:30.390 PDT
github.com/kubeflow/pipelines/backend/src/common/util.NewResourceNotFoundError
Error
2020-05-06 00:41:30.390 PDT
backend/src/common/util/error.go:150
Error
2020-05-06 00:41:30.390 PDT
github.com/kubeflow/pipelines/backend/src/apiserver/resource.(*ResourceManager).ReadArtifact
Error
2020-05-06 00:41:30.390 PDT
backend/src/apiserver/resource/resource_manager.go:884
Error
2020-05-06 00:41:30.390 PDT
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ReadArtifact
Error
2020-05-06 00:41:30.390 PDT
backend/src/apiserver/server/run_server.go:151
```

### PR DESCRIPTION
**Pull request by Bobgy**
**Description of your changes:**
Fixes https://github.com/kubeflow/pipelines/issues/3699

Changes:
* persistence agent only reads metrics artifact when it can find the output artifact in workflow status, so api server will not receive so many ReadArtifact requests that will fail for sure.

Manual Verification:
I deployed the persistence agent image: gcr.io/ml-pipeline-test/112bdfa56ddb54dbc05499d51ba6386362838459/persistenceagent@sha256:bc95106ebc84292652abb41b0088fa55a9b11dd3e6939d70c81b8ba64105568d on my cluster and verified running a few pipelines.

I can no longer see the confusing error messages while metrics are still reported properly.

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 
- [x] Do you want this pull request (PR) cherry-picked into the current release branch?

### CODE REVIEW

File: backend/src/agent/persistence/worker/metrics_reporter_test.go [hunk 1]
```diff
@@ -61,18 +87,50 @@ func TestReportMetrics_NoArtifact_NoOP(t *testing.T) {
...
+				"node-1": workflowapi.NodeStatus{
+					ID:    "node-1",
+					Phase: workflowapi.NodeSucceeded,
+				},
+			},
+		},
+	})
+	err := reporter.ReportMetrics(workflow)
+	assert.Nil(t, err)
+	assert.Nil(t, pipelineFake.GetReadArtifactRequest())
```
Comment (Bobgy) [inline backend/src/agent/persistence/worker/metrics_reporter_test.go:103]: Note, this is the reproducing test case. Without new changes, this will fail because persistence agent is still sending an artifact request in this case.

File: backend/src/agent/persistence/worker/metrics_reporter.go [hunk 2]
```diff
@@ -126,10 +126,24 @@ func (r MetricsReporter) collectNodeMetricsOrNil(
 	return reportMetricsRequest.GetMetrics(), nil
 }
 
-func (r MetricsReporter) readNodeMetricsJSONOrEmpty(runID string, nodeID string) (string, error) {
+func (r MetricsReporter) readNodeMetricsJSONOrEmpty(runID string, nodeStatus workflowapi.NodeStatus) (string, error) {
+	if nodeStatus.Outputs == nil || nodeStatus.Outputs.Artifacts == nil {
```
Comment (jingzhang36) [inline backend/src/agent/persistence/worker/metrics_reporter.go:130]: Thank you so much for the fix! It has been there for quite a while...

A quick question here: since mlpipine-metrics is option,  is it possible that user does specify a mlpipeline-metrics json file, but the workflow node fails to produce one? In other words, nodeStatus.Outputs.Artifacts don't contain "mlpipeline-metrics" but that indicates an error instead of indicating that users don't specify mlpipeline-metrics?  I am not familiar with the workflow.NodeStatus, so I am not sure if the info there is purely determined by the workflow runtime info or is also determined by the workflow static configuration.

Other than that, /lgtm /approve

Comment (Bobgy) [reply backend/src/agent/persistence/worker/metrics_reporter.go:130]: I am not sure too, but remember backend added optional to these artifacts for backwards compatability, So we have no way to clearly know a component should output one.
