### PR TITLE
fix(backend): support reading large doc from URL; Fixes #7652

### LINKED ISSUE #7652: [backend] Unable to upload a specific testing pipeline via URL
For the user journey test of upload pipeline. The testing pipeline https://github.com/kubeflow/pipelines/blob/master/sdk/python/kfp/compiler_cli_tests/test_data/xgboost_sample_pipeline.yaml was not able to be uploaded via URL.

### PR DESCRIPTION
**Pull request by Linchin**
**Description of your changes:**
Although we support [larger file sizes now](https://github.com/kubeflow/pipelines/blob/4e85352ed484db84dca5414f32c4a0c0eebf7c85/backend/src/apiserver/common/const.go#L62), the size for reading from URL is still constrained due to [package bufio's limit](https://pkg.go.dev/bufio#pkg-constants). This PR updated the related function for loading files from URLs, as well as added related unit tests.

Fixes #7652

**Checklist:**
- [x] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention).

### CODE REVIEW

**Comment by Linchin** [comment]
/test kubeflow-pipeline-backend-test
The backend test fail is caused by some flakiness in string comparison.

File: backend/src/apiserver/server/util.go [hunk 1]
```diff
@@ -29,17 +29,24 @@ import (
...
 
 func loadFile(fileReader io.Reader, MaxFileLength int) ([]byte, error) {
-	reader := bufio.NewReader(fileReader)
-	pipelineFile := make([]byte, MaxFileLength+1)
-	size, err := reader.Read(pipelineFile)
-	if err != nil && err != io.EOF {
-		return nil, util.NewInvalidInputErrorWithDetails(err, "Error read pipeline file")
+	reader := bufio.NewReaderSize(fileReader, MaxFileLength)
+	var pipelineFile []byte
+	for {
```
Comment (gkcalat) [inline backend/src/apiserver/server/util.go:34]: Let's add a TODO comment to improve the performance by setting a custom buffer size instead of 64KB. With `MaxFileLength` of 32MB we may end up with 500 iterations in this loop instead of reading the file in a single step.

**Review by gkcalat — COMMENTED** [review]
Thank you, @Linchin!

Aside from the small NIT below it looks good to me.

**Review by gkcalat — APPROVED** [review]
Thanks for adding the comment!

/lgtm
/approve
