### PR TITLE
fix(frontend): Fix the yaml cannot show in Safari browser issue. Fixes #4727

### LINKED ISSUE #4727: can't view pipeline yaml in Safari
### What steps did you take:

Tried to view yaml of an example pipeline via URL `.../#/pipelines/details/<pipeline-id>`

### What happened:

In chrome I was able to see the yaml:
image

In safari I couldn't:
image

### What did you expect to happen:

To be able to see the same yaml content in Safari as well.

### Environment:

Safari Version 14.0 (15610.1.28.1.9, 15610)
Chrome Version 86.0.4240.111 (Official Build) (x86_64)

How did you deploy Kubeflow Pipelines (KFP)?

We have our kustomize overlays over the manifests coming from https://github.com/kubeflow/manifests/archive/v1.1.0.tar.gz, we only install pipelines and metadata components with their requirements. We're working on a EKS cluster (v1.15.11-eks-065dce)

KFP version: 
https://github.com/kubeflow/pipelines/commit/988f5b02e4211dfff1c02eb0b9a52cbc69793364

### Anything else you would like to add:
We tested it in Safari in different computers, and we had the same problem.

### PR DESCRIPTION
**Pull request by fenglixa**
**Description of your changes:**
Yaml file cannot show with Safari browser, as below picture.
image

**Root-Cause**: react-ace Editor doesn't support in Safari when height or width is a percentage

After fixed, both Chrome and Safari browser are OK now:
image

**Checklist:**
- [ ] The title for your pull request (PR) should follow our title convention. [Learn more about the pull request title convention used in this repository](https://github.com/kubeflow/pipelines/blob/master/CONTRIBUTING.md#pull-request-title-convention). 

- [ x ] Do you want this pull request (PR) cherry-picked into the current release branch?

    [Learn more about cherry-picking updates into the release branch](https://github.com/kubeflow/pipelines/blob/master/RELEASE.md#cherry-picking-pull-requests-to-release-branch).

### CODE REVIEW

**Comment by fenglixa** [comment]
@Bobgy Could you provide /approved lable for this PR? Thanks!

File: frontend/src/pages/PipelineDetails.tsx [hunk 1]
```diff
@@ -325,8 +325,8 @@ class PipelineDetails extends Page<{}, PipelineDetailsState> {
               <div className={css.containerCss}>
                 <Editor
                   value={templateString || ''}
-                  height='100%'
-                  width='100%'
+                  height='640px'
```
Comment (Bobgy) [inline frontend/src/pages/PipelineDetails.tsx:328]: Thank you for the fix!
But can you explain why it didn't work in safari, and why do we need to hard-code a number here?
There might be better solutions that do not need a hard-coding, but also cross browser.

Comment (fenglixa) [reply frontend/src/pages/PipelineDetails.tsx:328]: Thanks @Bobgy, for your quick response!
The reason of the fixes refer to the link here: https://github.com/securingsincity/react-ace/issues/235
I tried the solutions mentioned in the link, but unfortunately, it's not work, we may have to make a fixed value there to show the yaml file with the scroll bar.

Comment (fenglixa) [reply frontend/src/pages/PipelineDetails.tsx:328]: @Bobgy , is that ok to you?

Comment (fenglixa) [reply frontend/src/pages/PipelineDetails.tsx]: Thanks @Bobgy , for your solutions.
1. I tried to upgrade react-ace to different versions (7.0.4, 7.0.5, 8.1.0, 8.0.0, 9.1.0, 9.2.0 etc..), but all of them couldn't work, I don't think react-ace addressed this issue in Safari.

2. **Finally, I used the solution-2 you proposed.**  It works after my fully tested, please help check the code. Whether it's OK to you now? Thanks very much!

**Comment by fenglixa** [comment]
@Bobgy I addressed your comments, could you please check, whether it's OK for you now? Thanks!

File: frontend/src/pages/PipelineDetails.tsx [hunk 2]
```diff
@@ -187,6 +187,14 @@ class PipelineDetails extends Page<{}, PipelineDetailsState> {
       versions,
     } = this.state;
 
+    const isSafari =
```
Comment (Bobgy) [inline frontend/src/pages/PipelineDetails.tsx:190]: Can you add a reference comment where the code comes from and explain why we need to add the hack?

**Review by Bobgy — COMMENTED** [review]
Thanks!
LGTM, just a minor nit picking

File: frontend/src/pages/PipelineDetails.tsx (hunk 2 above)
Comment (fenglixa) [reply frontend/src/pages/PipelineDetails.tsx:193]: @Bobgy , addressed, please check!

**Comment by fenglixa** [comment]
Seems it's the travis issue:
failed to retrieve log lines: failed to read log "build-log.txt": error getting pod log size: error getting size of pod log: container "test" in pod "38d5f6ba-32cf-11eb-9306-aeb63b108062" is terminated

**Comment by Bobgy** [comment]
/lgtm
/approve
Thanks! Test infra is flaky atm, wip for a fix

**Comment by Bobgy** [comment]
Can you fix `kubeflow-pipeline-frontend-test` test? There are at least formatting errors there
